### ISSUE TITLE
Devise parent controller and scope

### ISSUE THREAD

**Issue by nomasprime** [plataformatec/devise#4262] opened 2016-08-18 15:44 UTC
I've been trying to get Devise to work with a versioned API. Each version is partitioned but unfortunately it doesn't seem like you can change the Devise parent controller by scope.

I've seen several other issues based around the same problem.

**Comment by stringsn88keys** [comment] 2016-11-18 19:44
@habitullence Can you provide an example of the pattern that you're trying to implement?

**Comment by saadbinakhlaq** [comment] 2017-01-05 10:01
@stringsn88keys I am also having a similar issue here 
We have our web app and APIs for our mobile app
we have a couple of callbacks in our application controller and we don't want those to run for our API scope. Our API controller inherits from ActionController::Base, since DeviseController's parents controller is ApplicationController it will run all the callbacks. Is there a way for devise to inherit from ActionController::Base for API scope and ApplicationController for other use cases.

**Comment by vfonic** [comment] 2017-02-11 05:58
@saadbinakhlaq as one possible workaround, you could try to extract the needed functionality from ApplicationController into a concern and then override each devise controller with your own implementation that will have before_action which will run only for app and not for api.

**Comment by tegon** [comment] 2017-12-23 16:34
Hello @nomasprime, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:59
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-11 20:59 UTC
Labels: Needs more info
