### ISSUE TITLE
undefined method `rails5?' for Devise::Test:Module

### ISSUE THREAD

**Issue by tirdadc** [plataformatec/devise#4806] opened 2018-03-15 14:45 UTC
## Environment

- Ruby **[2.3.0]**
- Rails **[5.2.0.rc1]**
- Devise **[4.4.2]**

```ruby
describe "GET #index" do
    it 'redirects to login if not logged in' do
      get :index
      expect(response).to redirect_to(new_user_session_url)
    end
end
```

now throws this error:

```
1) Admin::ReleasesController GET #index redirects to login if not logged in
     Failure/Error: get :index

     NoMethodError:
       undefined method `rails5?' for Devise::Test:Module
```

The test itself hasn't changed. None of the other controllers specs result in this warning.

**Comment by tegon** [comment] 2018-03-15 16:36
Duplicate of #4808

**Closed by tegon** 2018-03-15 16:36 UTC
