### ISSUE TITLE
Upgrading from devise 4.4.1 to 4.4.2 causes NoMethodError

### ISSUE THREAD

**Issue by rmeritz** [plataformatec/devise#4811] opened 2018-03-16 20:36 UTC
## Environment

- Ruby ruby 2.4.2p198
- Rails 4.2.9
- Devise 4.4.2

## Current behavior

After the minor version upgrade my tests now fail with:

```
     NoMethodError:
       undefined method `rails5?' for Devise::Test:Module
````

**Comment by tegon** [comment] 2018-03-16 20:47
Duplicate of #4808

**Closed by tegon** 2018-03-16 20:47 UTC
