### ISSUE TITLE
Unable to Login after replacing a authentication system (which has been setup using RubyCAS) with devise authentication. I've connected to local db and I'm able to create users using rails c. But when I use those user credentials to login through UI in application. It throws me following error. I see 401 Unauthorized

### ISSUE THREAD

**Issue by vasudhar** [plataformatec/devise#4198] opened 2016-07-14 17:47 UTC
cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] 
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Started POST "/users/sign_in" for ::1 at 2016-07-14 12:39:05 -0400
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Processing by SessionsController#create as HTML
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"subdomain"=>"", "username"=>"vasudhar56", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Sign in"}
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Geokit is using the domain: localhost
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :authenticate_user!
false
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :set_current_account
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Account Load (0.6ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`name` IS NULL LIMIT 1
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Account Load (0.8ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`name` = ''  ORDER BY `accounts`.`id` ASC LIMIT 1
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :redirect_to_hijack_url
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :site_title
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :set_annoyer
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Completed 401 Unauthorized in 11ms (ActiveRecord: 2.0ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Processing by SessionsController#new as HTML
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"subdomain"=>"", "username"=>"vasudhar56", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Sign in"}
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Geokit is using the domain: localhost
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :authenticate_user!
false
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :set_current_account
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   CACHE (0.0ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`name` IS NULL LIMIT 1
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   CACHE (0.0ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`name` = 'l'  ORDER BY `accounts`.`id` ASC LIMIT 1  [["name", ""]]
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :redirect_to_hijack_url
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :site_title
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] :set_annoyer
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/devise-3.4.1/app/views/devise/shared/_links.html.erb (4.9ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_login_form_fields.html.haml (18.1ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_login_form.html.haml (20.7ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered users/sessions/new.html.haml within layouts/stripped (23.6ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered layouts/_doctype.html.haml (0.5ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_title.html.haml (0.6ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_action_stylesheets.html.haml (0.8ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_action_javascripts.html.haml (0.8ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered layouts/_javascript_css_app.html.haml (610.9ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_google_analytics.html.haml (0.8ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered layouts/_head.html.haml (618.7ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   SchoolYear Load (0.6ms)  SELECT  `school_years`.* FROM `school_years` WHERE `school_years`.`account_id` = 1 AND `school_years`.`begins` = '2016-07-01' AND `school_years`.`ends` = '2017-06-30'  ORDER BY `school_years`.`id` ASC LIMIT 1
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   CACHE (0.0ms)  SELECT  `school_years`.* FROM `school_years` WHERE `school_years`.`account_id` = 1 AND `school_years`.`begins` = '2016-07-01' AND `school_years`.`ends` = '2017-06-30'  ORDER BY `school_years`.`id` ASC LIMIT 1  [["account_id", 1], ["begins", Fri, 01 Jul 2016], ["ends", Fri, 30 Jun 2017]]
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered layouts/_time_traveller.html.haml (5.4ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` IS NULL  ORDER BY `users`.`id` ASC LIMIT 1
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered layouts/_sudoer.html.haml (2.4ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered layouts/_flash_messages.html.haml (0.7ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Tour Load (0.6ms)  SELECT  `tours`.* FROM `tours` WHERE `tours`.`account_id` = 1 AND `tours`.`path` = '/sessions/create'  ORDER BY `tours`.`id` ASC LIMIT 1
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1]   Rendered home/_tour.html.haml (0.6ms)
[cc947c92-556a-4a33-ad0b-47b57aa4ff9c] [::1] Completed 200 OK in 783ms (Views: 672.4ms | ActiveRecord: 1.8ms | Solr: 0.0ms)

**Comment by lucasmazza** [comment] 2016-07-14 21:25
Duplicate of #4197.

**Closed by lucasmazza** 2016-07-14 21:25 UTC
