### ISSUE TITLE
NoMethodError (undefined method login' for #<ActionDispatch::Request...>

### ISSUE THREAD

**Issue by ArbolEric** [plataformatec/devise#3357] opened 2014-12-04 20:45 UTC
rails 4.1, devise 3.4

I can create a user fine. The user just can't sign in (ie problem in POST users/sign_in, Devise::SessionsController#create). Here are some key variables from config/initializers/devise.rb:

    config.authentication_keys = [ :login ]
    config.request_keys = [ :login ]
    config.http_authenticatable = [false]

Here is the form from controllers/sessions/new.html.erb

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div><%= f.label :login %><br />
      <%= f.email_field :login, autofocus: true %></div>

      <div><%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "off" %></div>

      <% if devise_mapping.rememberable? -%>
         <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
     <% end -%>

     <div><%= f.submit "Log in" %></div>
     <% end %>

config/routes.rb

      devise_for :users, controllers: {
         sessions: 'users/sessions'
      }

models/User.rb

     class User < ActiveRecord::Base
       # Include default devise modules. Others available are:
       #  :confirmable, :lockable, :timeoutable and :omniauthable
       devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :trackable, :validatable,
             :authentication_keys => [:login]
         
       attr_accessor :login
    ....
    end

Here are the parameters submitted:

    {"utf8"=>"✓", 
        "authenticity_token"=>"yada",
        "user"=>{"login"=>"me@example.org", 
          "password"=>"[FILTERED]", 
          "remember_me"=>"0"}, 
        "commit"=>"Log in"}

I ended up solving my issue by changing lib/devise/strategies/authenticable.rb#148 to:

          def request_values
            keys = request_keys.respond_to?(:keys) ? request_keys.keys : request_keys
            values = keys.map { |k| self.request[self.scope][k] }
            Hash[keys.zip(values)]
          end

You can view the full stacktrace on [Stackoverflow](http://stackoverflow.com/questions/27215888/rails-4-devise-db-sign-in-nomethoderror-login-for-actiondispatchrequest).

Is this something I should create a pull request for??

**Comment by lucasmazza** [comment] 2015-01-26 19:53
Closing this one since it isn't a real issue with Devise and this is the expected behavior.

**Closed by lucasmazza** 2015-01-26 19:53 UTC
