### ISSUE TITLE
Devise shows different errors in paranoid mode when email exists and not exists

### ISSUE THREAD

**Issue by printercu** [plataformatec/devise#4568] opened 2017-06-23 09:06 UTC
Hi!

When email exist and wrong password is given, it shows `devise.failure.invalid` error. But when email is not registered, it shows `devise.failure.not_found_in_database `.

Should this be fixed?

**Comment by tegon** [comment] 2017-12-20 02:23
Hi @printercu, thanks for the report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:29
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-11 20:29 UTC
Labels: Needs more info
