### ISSUE TITLE
Dynamic url helpers not respecting default protocol

### ISSUE THREAD

**Issue by cartrdgeengineering** [plataformatec/devise#4217] opened 2016-07-24 22:55 UTC
Hi, I think I've identified a bug. In my routes file I have a simple devise directive with a default protocol:

```
devise_for :users, defaults: { protocol: :https }
```

And `user_password_url` correctly returns `https://host/users/password`. However, `password_url(:user)` is returning `http://host/users/password`, ignoring the default protocol.

This appears to be a bug.

**Comment by evertonts** [comment] 2017-01-18 19:11
Can you please provide a sample application that reproduces the error?

**Comment by tegon** [comment] 2017-12-13 22:48
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!

**Closed by tegon** 2017-12-13 22:48 UTC
