### ISSUE TITLE
Already initialized constant in production

### ISSUE THREAD

**Issue by Beengie** [plataformatec/devise#4722] opened 2017-12-12 23:46 UTC
## Environment

- Ruby 4.2.1
- Rails 5.1.4
- Devise 4.3.0

## Current behavior

The app performs fine in development. However, in production it seems that authenticatable.rb is being initialized more than once and it is trying to set the BLACKLIST_FOR_SERIALIZATION constant. I am not sure how to reproduce this error. I have searched through the docs and how to's but I cannot find anything regarding this. It worked fine in production then it stopped working when I added confirmable to the model. 

    2017-12-12T22:56:00.184107+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 38849 -e production`
    2017-12-12T22:56:06.185222+00:00 app[web.1]: /app/app/models/authenticatable.rb:57: warning: already initialized constant Devise::Models::Authenticatable::BLACKLIST_FOR_SERIALIZATION
    2017-12-12T22:56:06.185236+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/devise-4.3.0/lib/devise/models/authenticatable.rb:57: warning: previous definition of BLACKLIST_FOR_SERIALIZATION was here
    2017-12-12T22:56:06.185542+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
    2017-12-12T22:56:06.185576+00:00 app[web.1]: 	from /app/app/models/authenticatable.rb:62:in `<module:Authenticatable>'
    2017-12-12T22:56:06.185587+00:00 app[web.1]: 	from /app/app/models/authenticatable.rb:54:in `<module:Models>'
    2017-12-12T22:56:06.185591+00:00 app[web.1]: 	from /app/app/models/authenticatable.rb:6:in `<module:Devise>'
    ...

**Comment by tegon** [comment] 2017-12-19 10:45
Hi @Beengie, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-03 23:17
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-03 23:17 UTC
Labels: Needs more info

**Comment by Beengie** [comment] 2018-01-04 00:39
I'm not sure how I'm supposed to reproduce this error in isolation. I figured that those who wrote the  gem would have a better understanding of what would be required or changed from development to production mode including when authenticatable.rb is initialized. What would make the addition of confirmable to break my app in production?

**Comment by tegon** [comment] 2018-01-10 20:07
@Beengie Sorry about that. Unfortunately, I can't tell by just looking at this log what it might be happening here, that's why I asked for a sample application, so I could debug it to find the issue.
You can find the code where we include the modules here: https://github.com/plataformatec/devise/blob/master/lib/devise/models.rb#L79-L111
If you can do some debugging and paste some results here, maybe I can help.
