### ISSUE TITLE
cannot create 2 sessions in Minitest 

### ISSUE THREAD

**Issue by Russell108** [plataformatec/devise#4971] opened 2018-11-13 20:25 UTC
Rails 5.2.1
ruby 2.5.1p57 
Devise (4.5.0)

I Have a test controller using mini test with 2 users and follow the guidance of rails here
https://api.rubyonrails.org/v5.2.1/classes/ActionDispatch/IntegrationTest.html
**Current Behaviour**
The 2 sessions are not independent

Expected Behaviour
can test the 2 users independently ie a session for each user

Code. 

```ruby
require 'test_helper'

class SubjectsControllerTest < ActionDispatch::
  include Devise::Test::IntegrationHelpers
  test "the truth" do
     assert true
   end
   
   test "the lies of companies" do
     assert false
   end
   
  test "login and browse site" do
   #non_admin= login(:non_admin)
   site_admin = login(:site_admin)
   welsh_admin= login(:welsh_admin)
   
     site_admin.browses_site
     welsh_admin.access_unauthorised

    # Continue with other assertions
  end
  
  private
  
    module CustomDsl
       def browses_site
         get subjects_url #get "/subjects/all"
         assert_response :success
         assert_select 'div#course_subjects_title', 'Course Subjects'
       end
      
      def access_unauthorised
        get subjects_url #get "/subjects/all"
        assert_response :forbidden
        assert_equal "app cont You don't have access to this resource.<BR> Are you logged into your admin sections?", flash[:error] 
      end
    end

    def login(user)
      open_session do |sess|
        sess.extend(CustomDsl)
        u = users(user)
        sign_in u
        
      end
    end
   
   
end
```

**Comment by Russell108** [comment] 2018-11-13 20:34
I Have a test controller using mini test with 2 users and follow the guidance of rails here
https://api.rubyonrails.org/v5.2.1/classes/ActionDispatch/IntegrationTest.html
**Current Behaviour**
I can get the code to work but when I have 2 users the sessions get confused
Expected Behaviour
can test the 2 users independently


Code. 

`require 'test_helper'

class SubjectsControllerTest < ActionDispatch::IntegrationTest
  	include Devise::Test::IntegrationHelpers
   test "the truth" do
     assert true
   end
   
   test "the lies of companies" do
     assert false
   end
   
   
  
  test "login and browse site" do
   #non_admin= login(:non_admin)
   site_admin = login(:site_admin)
   welsh_admin= login(:welsh_admin)
   
     site_admin.browses_site
     welsh_admin.access_unauthorised

    # Continue with other assertions
  end
  
  private
  
    module CustomDsl
       def browses_site
         get subjects_url #get "/subjects/all"
         assert_response :success
         assert_select 'div#course_subjects_title', 'Course Subjects'
       end
      
      def access_unauthorised
        get subjects_url #get "/subjects/all"
        assert_response :forbidden
        assert_equal "app cont You don't have access to this resource.<BR> Are you logged into your admin sections?", flash[:error] 
      end
    end

    def login(user)
      open_session do |sess|
        sess.extend(CustomDsl)
        u = users(user)
        sign_in u
        
      end
    end
   
   
end`

**Comment by tegon** [comment] 2018-11-14 12:52
The factories `site_admin` and `welsh_admin` are from the same model?
If you can paste your devise models here that would help us to find the issue.

**Comment by Russell108** [comment] 2018-11-14 13:04
Yes they bare deliberately from the same model.
They are instances of the user model but are supposed to be different sessions as far as the app is concerned.

please find enclosed my code from the single devise model I have in my application

`class User < ApplicationRecord
		
	class AccessUnauthorised < StandardError; end
	# 	when user archived delete associations
	# 	cannot archive a user if they are manager of area
	# 	de activate affiliations
	#  validate on update if available_workcentres empty then centre_id nil

  # Include default devise modules. Others available are:
  #  , :validatable:rememberable,  :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,:lockable, :timeoutable,
         :recoverable, :trackable, :confirmable
	attr_accessor :send_email , :current_password

	#attribute :colour, :string

	# enable logging with paper trail gem


	strip_attributes :collapse_spaces => true
	
	#after_save  :archive_associations,    :if => Proc.new{ |u|  u.archived }
	before_destroy :verify_destroy 
	before_validation :titleize_name, :unless => Proc.new{ |u|  u.surname.blank? or u.forename.blank? }
	before_validation :downcase_email, :unless => Proc.new{ |u|  u.email.blank?  }
	#before_validation :locked_at_follows_archiving
	
	around_save  :de_activate_affiliations_and_memberships, :if => Proc.new{ |user| user.archived_changed?  &&  (user.archived==true)}
	around_save :remove_associations, :if => Proc.new { |user| user.archived_changed?  &&  (user.archived==true)} 

	#######################################   validations  ################################
	validates_uniqueness_of :email#, :case_sensitive => false,  :if => :email_changed?
#	validates_format_of :email, :with => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
#	##validates_presence_of  :password, :on=>:create
	validates_presence_of  :email
	validates_format_of :email, :with => /.+@.+\..+/i
	##validates_confirmation_of :password, :on=>:create
	validates_length_of :password, :within => Devise.password_length , :allow_blank => false,    :if => :password_validation_required?
	validates_confirmation_of :password
	validates_presence_of :forename, :surname
	validates_length_of  :forename, minimum: 2, too_short: 'please enter at least 2 characters'
	#validates_format_of :colour, :with =>  /\A[a-z\s]+\Z/  , :allow_blank => true,
	#					message: "please use characters a-z or space"
#
#	validates :email, :presence => true, :email => true
	validate :no_stupid_passwords ,    :if => :password_validation_required?
	validate :manages_no_areas?, :if =>Proc.new{|user| user.archived_changed? && (user.archived == true) }
	validate :on_admin_centre_change, :if =>Proc.new{|user| user.centre_id_changed? && !user.centre_id.blank?}
	validate :validate_centre , :if =>Proc.new{|user| user.centre_id_changed? && !user.centre_id.blank?}
	validate :email_against_unconfirmed_email

#######################################   associations ################################ns 
	has_paper_trail ignore: [:failed_attempts, :sign_in_count, :current_sign_in_at, :last_sign_in_at]
	 # 10 mean you article will have 11 version include 'create' version
  	PaperTrail.config.version_limit = 7
	
	has_many :colleagueships, dependent: :destroy
	has_many :admin_areas, through:  :colleagueships, :source => :area
	
	
	has_many :areas, foreign_key: :manager_id

	has_many :affiliations
	has_many :guests
	has_many :students
	has_many    :memberships,:inverse_of => :user,  dependent: :destroy

	# transcript related associations
	has_many :transcripts
	has_many :scribeships,     :dependent => :destroy
	
  	#has_many    :meets, through: :memberships

	has_many :assignments
	has_many :work_centres,->{distinct}, :through=>:assignments, :source => :centre
	
	has_many :acquired_packages, dependent: :destroy
	has_many :packages, through: :acquired_packages
	has_many :acquired_resources,  dependent: :destroy
	has_many :resources, through: :acquired_resources
	has_many :acquired_groups ,  dependent: :destroy
	has_many :groups, through: :acquired_groups
	#has_many :contributions
	has_one :speaker
	has_many :allocated_orders
	has_many :allocated_order_resources, through: :allocated_orders
	has_many :allocated_carts, -> { where("status_id = 1")}, class_name: "AllocatedOrder"
	has_many :allocated_cart_resources, through: :allocated_carts , :source=> :order_resources
	belongs_to	:centre, optional: true
	belongs_to :talk_type, optional: true
	belongs_to :sponsor, class_name: "User",optional: true
	has_many :recipientships
	has_many :family_digests, through: :recipientships
	  
	

#######################################   scopes  ################################

	  scope :family, ->{  where("talk_type_id IS NOT Null and family_mailings IS true and archived is false")}
	  scope :current, ->{  where(:archived=> false)}
	  scope :archived ,->{ where(:archived=> true)}
	
	  scope :by_name_or_email,lambda{|name | where("forename ILIKE ? or surname ILIKE ? or email ILIKE ?",
	                                               "%#{name}%","%#{name}%", "%#{name}%")}

	  scope :by_name_or_email_split,lambda{|name_0, name_1 | where("(forename ILIKE ? or surname ILIKE ? or email ILIKE ?) and
	  																(forename ILIKE ? or surname ILIKE ? or email ILIKE ?)",
	                                               "%#{name_0}%","%#{name_0}%", "%#{name_0}%","%#{name_1}%","%#{name_1}%", "%#{name_1}%")}
	  scope :select_for_index, ->{ select("users.id,users.email,users.forename, users.surname, CONCAT_WS(' ', users.forename, users.surname) AS fullname,\
          users.archived,users.unconfirmed_email,users.confirmed_at")}
	  scope :select_for_show, ->{ select("users.id,users.email, CONCAT_WS(' ', users.forename, users.surname) AS fullname,\
          users.archived,users.unconfirmed_email,users.confirmed_at,users.d_o_b, talk_types.name AS talk_type_name,\
                      CONCAT_WS(' ', sponsors_users.forename, sponsors_users.surname) AS sponsors_name, users.sponsor_notes, users.family_mailings")}
	  scope :select_fullname, ->{ select("users.id, CONCAT_WS(' ', users.forename, users.surname) AS fullname")}
	 # scope :to_redistribute, lambda{|family_digest_id | where("users.family_digest_id != ?",family_digest_id )}
	
	#find users who have acquired a package or resource for a happening
	 scope :acquireships_for_happening,lambda{|happening_id |
	 	where("(packages.happening_id = ?) or (recordings.happening_id = ?)",happening_id,happening_id )   \
	 	.left_outer_joins({acquired_packages: :package},{acquired_resources: {resource: :recording}})
	 }


	#====================================   Public Methods   ===============================================

	#checking if user has a Centre role or is site admim
	def has_assignment?(role_array)
		role_array =[role_array].flatten
		if( role_array.include? "Site")
		   self.assignments.joins(:role)
		   .where("(roles.name ='Site') OR 	(roles.name in (?) and assignments.centre_id =?)", role_array,self.centre_id).any?
		 
		else
		  self.assignments.joins(:role)\
         .where("roles.name in (?) and assignments.centre_id =?",role_array,self.centre_id ).any?
       
		end
	end

	# checking if has role transcription Admin

	def is_transcription_admin?
		   self.assignments.joins(:role)
		   .where("(roles.name ='Transcription')").any?
	end

	# used including for drop down to select centre
	def available_workcentres
		if self.has_assignment?( "Site")
			Centre.all 
		else
			work_centres
		end
	end

	#def fullname
	#  fore_name = forename || ''
	#  sur_name = surname || ''
	#  fullname= (fore_name.strip.capitalize + "&nbsp;" + sur_name.strip.capitalize).html_safe
	#end
#
	def plain_fullname
	  fore_name = forename || ''
	  sur_name = surname || ''
	  fullname= (fore_name.strip.capitalize + " " + sur_name.strip.capitalize)
	end

	#check if confirmation_token has not time expired  returns false if expired
	def confirmation_token_current?
	  User.confirm_within && self.confirmation_sent_at && (Time.now < self.confirmation_sent_at + User.confirm_within)
	end
	
	
	def confirmation_current?
	  return false if pending_reconfirmation?
	  return false unless confirmed?
	  return true
	end
	
	def update_admin_centre(params_user)
	#	unless valid_password?(params_user[:forename]) 
			errors.add(:password, "Password invalid")
			self.update_attributes(params_user)
	#	end
	end


	 # ensure user account is active  
	def active_for_authentication?  
    super && !archived 
	end  


	 # provide a custom message for a archived account   
	def inactive_message   
		!archived ? super : :archived_account 
	end  
  
   def timeout_in
       # 30 minutes = 1800
       # 15 minutes =900
       # 6 hours   =21600
   # 30.minutes
     if (centre_id.blank? && !transcription_admin && admin_areas.empty?)
   #  	logger.debug "\n\n acting as user centre_id.blank? #{centre_id.blank?}, !transcription_admin #{!transcription_admin}, admin_areas.empty? #{admin_areas.empty?} \n\n"
         trusted_ip  ? 6.hours : 30.minutes
     else
    # 	logger.debug "\n\n acting as admin centre_id.blank? #{centre_id.blank?}, !transcription_admin #{!transcription_admin}, admin_areas.empty? #{admin_areas.empty?} \n\n"
         trusted_ip  ? 30.minutes : 1000.seconds
     end

   end

	#====================================   Private Methods   ===============================================

	private
	
	def brick_wall				
		self.errors.add(:base, "brickwall in  order")
		return false
	end	
	
	def password_validation_required?
	   password != nil
	end
	  
	# def stopping
	# 	errors.add(:password, "stopping.") 
	# 	return false
	# end
	  def no_stupid_passwords
	     #  allowed=true
	      
	       ( return false)if (forename.blank? || surname.blank?)
	        if ((self.password.downcase.strip.include? self.forename.downcase) || (self.password.strip.downcase.include? self.surname.downcase))
	         errors.add(:password, "You cannot use your forename or surname sequentially in your password.") 
	    
	      end
	
	      if (self.password.downcase.strip.include? self.email.downcase)
	          errors.add(:password,"You cnnot use your email sequentially in your password.")  
	         
	      end
	      
	      BannedPassword.all.collect(&:name).each do |banned|
	        if ((self.password.strip.include? banned) )
	      
		     errors.add(:password, "As it stands your chosen password  is considered insecure ==>\"#{banned}\" <==. 
		       <BR>Please adapt your password or choose another. For example: use a number 0 instead of a letter O. <BR>Thank you!!".html_safe )
		
	              throw(:abort)
	        end
	      end
	    end
	
	  def titleize_name
	    self.forename= self.forename.titleize
	    self.surname= self.surname.titleize
	  end

	  def downcase_email
	  	self.email.downcase!
	  end

	  
	def manages_no_areas?
		unless areas.empty?  
			
			errors.add(:archived, "cannot be archived manages an Area")
		end
	end
	
	def verify_destroy
		allow_destroy=    true
	
		unless acquired_packages.empty?           
		  errors.add("Packages",  " have been acquired/purchased." )
		  allow_destroy=   false
		end
		
		unless acquired_resources.empty?           
		  errors.add("Products",  " have been acquired/purchased." )
		  allow_destroy=   false
		end
	   
		unless affiliations.empty?           
		  errors.add(:courses,  " is a member of one or more Courses." )
		  allow_destroy=   false
		end
	
		unless memberships.empty?           
		  errors.add(:projects,  " is a member of one or more Events." )
		  allow_destroy=   false
		end
	      
		

		unless assignments.empty?           
		  errors.add(:assignments,  " Administration roles exist." )
		  allow_destroy=    false
		end

		unless areas.empty?           
		  errors.add(:areas,  " Manages one or more areas." )
		  allow_destroy=    false
		end
	   

	   	unless transcripts.empty?           
		  errors.add("Transcripts",  " Manages several transcripts." )
		  allow_destroy=   false
		end
	   ##   errors.add(:base, "Brick Wall testing")
	   ##   allow_destroy=    false
	  
	     (throw :abort )unless allow_destroy
	end
	
	  def de_activate_affiliations_and_memberships
	  	yield
	     self.affiliations.each do |affiliation|
	        affiliation.update_attribute(:active, false)
	    end
	    self.memberships.each do |membership|
	        membership.update_attribute(:active, false)
	    end
	  end

	  def remove_associations
	  #	self.forename = self.forename + " abc" 
	  	yield
	  	#self.associations.clear
	  end

	  # valiation when changing admin centre
	def on_admin_centre_change
		
		unless self.valid_password?(current_password)
			errors.add(:current_password, "password invalid!")
			
		end
	end

	 def validate_centre
	 	unless  ((self.has_assignment? "Site") ||  (self.work_centre_ids.include? self.centre_id) )
	 		errors.add(:centre, "centre invalid!")
			  
	 	end
	 end

	 def email_against_unconfirmed_email 
	 	if User.where("unconfirmed_email = ? and id !=?",self.email, self.id).any?
	 		errors.add(:email, "email already taken though as yet unconfirmed!!!")
	 	end
	 end


end
`

**Comment by tegon** [comment] 2018-11-14 13:30
Users from the same model cannot coexist in the same session by default. That's because we use [Warden scopes](https://github.com/wardencommunity/warden/wiki/Scopes) to keep the users in the session. By default, devise creates a Warden scope based on the model's name, so when you sign in with the user that has the ID = 1, the session looks like this:
```ruby
{ "warden.user.user.key" => 1 }
```
Where the second "user" is the scope.

In order to have multiple users in the session, you need to use different scopes. You can either create different models or specify the scope in the `sign_in` method:
```ruby
sign_in users(:site_admin), scope: :site
# session => { "warden.user.site.key" => 1 }
sign_in users(:welsh_admin), scope: :welsh
# session => { "warden.user.site.key" => 1, "warden.user.welsh.key" => 2 }
```

**Comment by Russell108** [comment] 2018-11-14 14:09
I think you have missed the point.
I aim well aware off what you mention but in a web site you can have many users of the same Model each with their own session logged in at the same time

I am setting this up for testing so I don't need to create the same test for each type of logged in user.

I have troll based authorisation on my web site I don't use devise for this authorisation.
I am using the logic from rails if you go to the Links I provided you will see in mini test you can test the same assertions but use 2 users each with a unique session at the same time.
Here is the link again

https://api.rubyonrails.org/v5.2.1/classes/ActionDispatch/IntegrationTest.html

**Comment by Russell108** [comment] 2018-11-14 15:45
Ok I have had success if I ignore the  Devise::Test::IntegrationHelpers but instead manually login each user attached to the session in the private login method.

So what happens now is I have 2 users, in the test suite each logged in with devise and have their own unique session.

I tried. attaching the devise login helper in the same way to the uniques session but it did not work.


for clarity here is the method

```
def login(user)
  open_session do |sess|
    sess.extend(CustomDsl)
    u = users(user)
    sess.post user_session_path("user[email]"    => u.email,  "user[password]" => "password")
   # /users/sign_in
  end
end
```


And here is the whole test file



```
require 'test_helper'

class SubjectsControllerTest < ActionDispatch::IntegrationTest
    #include Devise::Test::IntegrationHelpers
    setup do
    	@recording = recordings(:first_event_rec_1)
    end
   test "the truth" do
     assert true
   end
   
   test "the lies of companies" do
     assert false
   end
   

  test "login and browse site" do
      assert true
   site_admin = login(:site_admin)
   welsh_admin= login(:welsh_admin)
   
     site_admin.browses_site
     welsh_admin.access_unauthorised
  
    # Continue with other assertions
 end
  
  private
  
    module CustomDsl
       def browses_site
         get subjects_url #get "/subjects/all"
         assert_response :success
         assert_select 'div#course_subjects_title', 'Course Subjects'
        
       end
      
      def access_unauthorised
        get subjects_url #get "/subjects/all"
        assert_response :forbidden
        assert_equal "app cont You don't have access to this resource.<BR> Are you logged into your admin sections?", flash[:error] 
      end
    end

    def login(user)
      open_session do |sess|
        sess.extend(CustomDsl)
        u = users(user)
        sess.post user_session_path("user[email]"    => u.email,  "user[password]" => "password")
       # /users/sign_in
      end
    end
   
 
   
end
```

**Comment by Russell108** [comment] 2018-11-15 12:32
I have no idea why this has been marked needs more information.
Basically its your  Devise::Test::IntegrationHelpers that don't seem to do the job
I have provided what you have asked for. Please state what information you need

Thanks

**Comment by tegon** [comment] 2018-11-20 20:45
> I have no idea why this has been marked needs more information.
I've added the label when I first asked for more information.

> but in a web site you can have many users of the same Model each with their own session logged in at the same time
Sure, I'm just trying to understand how you're trying to handle this because Devise uses Warden to store the users in the session, and as I mentioned, this won't work by default with the same model. It can work, of course, with some changes.

Bottom line is, I haven't understood exactly how your application is structured, so I think the best way for me to help is if you provide us a sample application that reproduces this issue in isolation. Can you provide us one, please?

**Comment by Russell108** [comment] 2018-11-20 22:53
Yes I can see you are still talking about my application rather than the test environment.

As per the details I have already posted in the test file I set up 2 devise users each with a different session 

I do this manually and it works if I use the devise test helpers it does not

Did you look at the link I sent, it sounds like yo didn’t. 

I will set up a test app

**Comment by Russell108** [comment] 2018-11-21 20:02
here is the test project
https://github.com/Russell108/mydevise

There is a test file called test/controllers/user_flows_test.rb

which demonstrates logging in as 2 separate users with 2 separate sessions in a test suite using devise login pagesI cannot do the same using the devise test helpers

**Comment by Russell108** [comment] 2018-11-21 21:54
Yes exactly 

Thank you

**Comment by tegon** [comment] 2018-11-21 21:59
Ok, I'm going to close this then.

Thanks!

**Closed by tegon** 2018-11-21 21:59 UTC
Labels: Needs debugging
