### ISSUE TITLE
Had to login twice when user tries to re-activate the account

### ISSUE THREAD

**Issue by alphamarket** [plataformatec/devise#4484] opened 2017-04-02 12:49 UTC
I use [act as paranoid](https://github.com/ActsAsParanoid/acts_as_paranoid) for soft deletion and deactivation of accounts, and for reactivation, I use the following:

reference: [User.authenticate(.)](https://github.com/plataformatec/devise/wiki/How-To:-Find-a-user-when-you-have-their-credentials)

```ruby
class Users::SessionsController < Devise::SessionsController
  # POST /resource/sign_in
  def create
    # pre-fetch the user to see if it is has been deactivated or not
    user = User.authenticatesign_in_params[:phone_number], sign_in_params[:password], "only_deleted")
    # if this is a comming back user, recover the user instance to allow the devise to the rest of the job
    if user
      user.recover
      user.save
      flash[:alert] = 'you account re-activated'
    end
    # call the devise
    super
  end
end
```
But when the user tries to reactivate the account, it had to login twice! by part's code is clear, this is definetly comes from devise, how to fix this?

**Comment by gurgelrenan** [comment] 2017-10-27 00:19
Perhaps you could provide a example app to reproduce the bug? Take a look at https://github.com/plataformatec/devise/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by tegon** [comment] 2017-12-24 13:18
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-24 13:18 UTC
