### ISSUE TITLE
Devise request_format helper method returns */* instead of :json

### ISSUE THREAD

**Issue by pablocrivella** [plataformatec/devise#4707] opened 2017-11-27 10:19 UTC
## Environment

- Ruby **2.4.1**
- Rails **5.1.5**
- Devise **4.3.0**

## Current behavior

When making a request without setting the format explicitely on the url, Devise `request_format` helper method returns `*/*` which causes the following error:

```
NameError (undefined local variable or method `flash' for #<RegistrationsController:0x007febe49ba690>):
```

## Expected behavior

Devise `request_format` helper method should return `:json`

**Comment by feliperenan** [comment] 2017-11-27 21:25
HI @pablocrivella 

Could you sent to us an example to reproduce this error?

**Comment by tegon** [comment] 2017-12-29 20:20
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-29 20:20 UTC
Labels: Needs more info
