### ISSUE TITLE
Issue with capitalization when humanizing authentication keys in failure flash message

### ISSUE THREAD

**Issue by cyrusstoller** [plataformatec/devise#4900] opened 2018-07-06 06:59 UTC
Thank you so much for building something that I use in almost every rails project I start.

## Environment

- Ruby **2.5.1**
- Rails **5.2.0**
- Devise **4.4.3**

## Current behavior

When looking at the `devise.failure.not_found_in_database` and `devise.failure.invalid` error messages, it currently says "Invalid Email or password." when the `authentication_keys` = `:email`. To me this is strange capitalization. I'm not expecting "Email" to be capitalized.

## Expected behavior

I like that this takes the `authentication_keys` and makes them human readable, but I wish that it would make them lower case so that it read, "Invalid email or password." instead.

**Comment by cyrusstoller** [comment] 2018-07-06 07:15
I'm pretty sure this is the line that would need to be changed.

https://github.com/plataformatec/devise/blob/master/lib/devise/failure_app.rb#L106

**Comment by Arepo** [comment] 2018-07-12 15:02
I agree with the OP fwiw - this isn't the behaviour I'd expect, all the more so for the fact that it changed in an earlier version

**Comment by tegon** [comment] 2018-07-12 16:59
Duplicate of #4095. There's already a pull request opened (#4834) but it needs some changes before it can be merged.

**Closed by tegon** 2018-07-12 16:59 UTC

**Comment by archonic** [comment] 2019-04-17 23:39
This issue is still present in 4.6.2. Was it intentionally merged into the 5-rc branch?

**Comment by tegon** [comment] 2019-04-18 11:44
@archonic Yes - because this change does not preserve backwards compatibility.

We are going to release in version 5 though.
