### ISSUE TITLE
Rails 6: Devise Testing w/  Fixtures Broken?

### ISSUE THREAD

**Issue by trendwithin** [plataformatec/devise#5095] opened 2019-07-10 01:54 UTC
- Ruby **2.5.0**
- Rails **Rails 6.0.0.rc1**
- Devise **'devise', '~> 4.6', '>= 4.6.**

Devise Sign In Test that worked previously in test suites using Rails 5 are currently breaking using Rails 6.

fixtures.yml
`user_vic: email: vic@theshield.net`
 `  encrypted_password: <%= Devise::Encryptor.digest(User, 'password') %`

## Integration Test
```
require 'test_helper'

class UserSignInTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  setup do
    @user = users(:user_vic)
  end

  test 'sign in existing user' do
    get user_session_path
    sign_in(@user)
    assert_response :redirect
  end
end
```

## Expected behavior
Expecting a Devise redirect but 200 OK response retured
`Expected response to be a <3XX: redirect>, but was a <200: OK>`

## System Test
```
require "application_system_test_case"

class UserSignInTest < ApplicationSystemTestCase
  # System Test Error: BCrypt::Errors::InvalidHash: invalid hash
  test 'valid credential user logs in' do
    visit user_session_path
    fill_in 'user[email]', with: 'vic@theshield.net'
    fill_in 'user[password]', with: 'password'
    find('input[name="commit"]').click
  end
end
```

## Behavior

```
Error:
UserSignInTest#test_valid_credential_user_logs_in:
BCrypt::Errors::InvalidHash: invalid hash
```

## Partial Stack Trace

```
2019-07-09 18:46:40 -0700: Rack app error handling request { POST /users/sign_in }
#<BCrypt::Errors::InvalidHash: invalid hash>
/Users/Strawman/.gem/ruby/2.5.0/gems/bcrypt-3.1.12/lib/bcrypt/password.rb:60:in `initialize'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/encryptor.rb:16:in `new'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/encryptor.rb:16:in `compare'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/models/database_authenticatable.rb:68:in `valid_password?'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/strategies/database_authenticatable.rb:13:in `block in authenticate!'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/models/authenticatable.rb:83:in `valid_for_authentication?'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/strategies/authenticatable.rb:38:in `validate'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/lib/devise/strategies/database_authenticatable.rb:13:in `authenticate!'
/Users/Strawman/.gem/ruby/2.5.0/gems/warden-1.2.8/lib/warden/strategies/base.rb:54:in `_run!'
/Users/Strawman/.gem/ruby/2.5.0/gems/warden-1.2.8/lib/warden/proxy.rb:369:in `block in _run_strategies_for'
/Users/Strawman/.gem/ruby/2.5.0/gems/warden-1.2.8/lib/warden/proxy.rb:365:in `each'
/Users/Strawman/.gem/ruby/2.5.0/gems/warden-1.2.8/lib/warden/proxy.rb:365:in `_run_strategies_for'
/Users/Strawman/.gem/ruby/2.5.0/gems/warden-1.2.8/lib/warden/proxy.rb:335:in `_perform_authentication'
/Users/Strawman/.gem/ruby/2.5.0/gems/warden-1.2.8/lib/warden/proxy.rb:133:in `authenticate!'
/Users/Strawman/.gem/ruby/2.5.0/gems/devise-4.6.2/app/controllers/devise/sessions_controller.rb:19:in `create'
```

**Comment by rafaelfranca** [comment] 2019-07-16 02:35
Can you provide an example application that reproduce the issue?

**Comment by trendwithin** [comment] 2019-07-16 18:33
App I'm currently working on [GitRepo Blocks](https://github.com/trendwithin/blocks)

I commented out the redirect so this will need to be uncommented before running: `rails test test/integration/users/user_sign_in_test.rb`

I have the system test commented out as well since it breaks so those will need to be removed before running `rails test test/system/users/user_sign_in_test.rb`  I just ran the test again with byebug in order to confirm this with a screenshot from the browser.

<img width="1050" alt="Screen Shot 2019-07-16 at 11 06 55 AM" src="https://user-images.githubusercontent.com/8145031/61318977-1dab4f80-a7bb-11e9-9137-b4dd32835853.png">

I haven't seen any modification in the README regarding fixtures so I've used the same as in my Rails 5 projects.  Additionally, sign in and redirect work perfectly fine in Dev.

**Comment by tegon** [comment] 2019-08-01 17:43
@trendwithin I took a look at your application and the tests fail because of two things:

1 - In the fixtures file, you forgot to close the ERB tag with `>`, so the password hash was being generated with the literal "<%= Devise::Encryptor.digest(User, 'password') %" string.
2 - The integration test is using the `sign_in` helper, which mimics that behavior to make it easier to write tests that need a signed-in user. That's why no redirects are performed there - no HTTP requests are performed either.

I'm closing this issue then. Thank you.

**Closed** 2019-08-01 18:57 UTC

**Comment by trendwithin** [comment] 2019-08-01 21:53
For the life of me I did not even see that and I stared at it for a long time.  Thanks.
