### ISSUE TITLE
re-opening #2871

### ISSUE THREAD

**Issue by chocnut** [plataformatec/devise#3340] opened 2014-11-24 17:20 UTC
I got the same issue with @jimiguru I'm not really sure why the reset token saved in the db didn't match when users updating their new password. can anybody help us with this? thanks!

**Comment by josevalim** [comment] 2015-02-13 08:48
Thank you @rubyrider. We still can't reproduce this issue to, so we are closing it for now!

**Closed by josevalim** 2015-02-13 08:48 UTC
