### ISSUE TITLE
Infinite redirection loop after sign in/ sign up caused by `require_no_authentication` DeviseController method

### ISSUE THREAD

**Issue by otamm** [plataformatec/devise#4718] opened 2017-12-05 21:29 UTC
Environment:
- Ruby 2.3.1
- Rails 5.1.4
- Devise 4.3.0

So, for the first time in my life I'm having trouble with Devise (by the way, great job for the gem). Once I log in or sign up an user, there's an infinite redirection loop inside the ``require_no_authentication`` method defined in the main ``DeviseController`` . I usually define my own redirection methods after sign in/sign up and this time was no different, however, after some frustrating moments I simply commented out all of my defined methods and the problem was still persisting.
As a very improvised solution, I've copied the ``DeviseController`` into my own app and commented out all of this method's code still with all of my own methods commented out and apparently the most immediate problem was solved and the user was being successfully logged in, even though there was still a call from this method after ``sessions#create``. It seems to me that this was not supposed to happen.
I've attached an image with my modifications of ``devise_controller.rb`` . As you can see, there's nothing special about it except for a ``puts`` statement to check for the method call in the application logs and the method's body commented out.

![screen shot 2017-12-05 at 7 28 50 pm](https://user-images.githubusercontent.com/6130761/33631741-9a638c38-d9f2-11e7-9e3f-833bd5dcf1e8.png)

**Comment by otamm** [comment] 2017-12-05 21:31
Also important to note that the issue stays the same while tested in different browsers and in private windows, so I've already checked for a possible session/cookie issue.

**Comment by tegon** [comment] 2017-12-14 21:32
Hello @otamm, thanks for your report.
Can you provide us a sample application that reproduces the issue? That would help us to find the issue.

Thank you.

**Comment by tegon** [comment] 2018-01-03 23:17
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-03 23:17 UTC
Labels: Needs more info

**Comment by newfylox** [comment] 2018-12-27 17:59
I cannot tell you if it's because of `require_no_authentication` method, but I can tell you that I have random infinite redirection loops in my application after signing in. At first I thought it was because of the `force_ssl` option in **production**, but it does this in **development** environment as well (only `HTTP`).

Nothing special in my code, I'm only using `before_action :authenticate_amin!` helper in my controllers. Could using `devise_token_auth` gem in the same project (for api call) cause bad experiences?

**Comment by w-A-L-L-e** [comment] 2019-10-31 11:58
Also just ran into this. Same issue getting redirect_loop registrations controller new action is redirecting to itself when user is signed in.

```
Started GET "/" for ::1 at 2019-10-31 12:53:43 +0100
Processing by Users::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/devise
  Rendered devise/shared/_error_messages.html.erb (0.9ms)
  Rendered devise/shared/_links.html.erb (1.2ms)
  Rendered devise/registrations/new.html.erb within layouts/devise (25.8ms)
Completed 200 OK in 77ms (Views: 74.7ms | ActiveRecord: 0.0ms)


Started GET "/" for ::1 at 2019-10-31 12:53:46 +0100
Processing by Users::RegistrationsController#new as HTML
  Rendering devise/registrations/new.html.erb within layouts/devise
  Rendered devise/shared/_error_messages.html.erb (0.5ms)
  Rendered devise/shared/_links.html.erb (1.3ms)
  Rendered devise/registrations/new.html.erb within layouts/devise (19.2ms)
Completed 200 OK in 100ms (Views: 99.5ms | ActiveRecord: 0.0ms)

.... and this repeats until the browser crashes with too many redirects...

```
