### ISSUE TITLE
Deprecation warning in Rails 6.0.0.rc1 for email  uniqueness validation

### ISSUE THREAD

**Issue by shanehofstetter** [plataformatec/devise#5064] opened 2019-04-25 10:03 UTC
## Environment

- Ruby 2.5.3
- Rails 6.0.0.rc1
- Devise 4.6.2

## Current behavior

```
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :email attribute in User model, pass `case_sensitive: true` option explicitly to the uniqueness validator.
```

## Expected behavior
No deprecation warning

## Possible solution

Since case_sensitive seems to be an option since rails 5 this could be added without breaking backwards compatibility: 
```ruby
# devise/models/validatable.rb
if Devise.activerecord51?
  validates_uniqueness_of :email, allow_blank: true, if: :will_save_change_to_email?, case_sensitive: true
[...]
```

**Comment by tegon** [comment] 2019-04-25 20:57
Hello @shanehofstetter, thanks for reporting this.

Yeah, that seems like a good solution. Do you want to open a pull request for this or should I assign it for someone else?

**Comment by Vasfed** [comment] 2019-04-26 11:23
Opened a PR for this: https://github.com/plataformatec/devise/pull/5065

**Closed** 2019-05-04 17:41 UTC
Labels: PR attached

**Comment by mgmodell** [comment] 2019-09-15 00:38
@Vasfed I killed all spring processes and then, for good measure, I went ahead and restarted my Mac and still I get the warnings.

**Comment by tegon** [comment] 2019-09-16 18:33
@mgmodell Can you provide us a sample application that reproduces the issue?

**Comment by mgmodell** [comment] 2019-10-01 13:03
@tegon - Sorry about this (and for taking so long to respond). It turns out the error seems to be coming from devise-multi_email.

**Comment by vesh95** [comment] 2020-05-14 19:22
How to hide this message on start rspec?
