### ISSUE TITLE
Confirmation emails not sent when using after_create

### ISSUE THREAD

**Issue by jeremylynch** [plataformatec/devise#4416] opened 2017-01-31 13:17 UTC
I am processing stripe payments during user signup in an `after_create`. Since this uses the stripe API it takes some seconds to complete. However, when this is complete it appears that `send_on_create_confirmation_instructions` is not called and the email is not sent. 

Below is the code from the confirmable module, can an `after_create` coexist with this `after_commit`?

```ruby
 after_commit :send_reconfirmation_instructions, on: :update, if: :reconfirmation_required?
```

**Comment by thomasthejn** [comment] 2017-05-07 11:41
I have the same problem, with just using after_create in my user model. Then confirmation e-mails is not send.

**Comment by tegon** [comment] 2017-12-24 13:13
Hello @jeremylynch, thanks for your report.
`after_commit` is called after `after_create`, so I guess it should work.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:59
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-11 20:59 UTC
Labels: Needs more info
