### ISSUE TITLE
failure_app broken on JRuby

### ISSUE THREAD

**Issue by batasrki** [plataformatec/devise#4096] opened 2016-05-09 01:44 UTC
This commit, https://github.com/plataformatec/devise/commit/7025f968c690775de42cf31a969c0e97913df59f, made it so that login failures are broken on JRuby. All Devise versions after this commit will not work on JRuby, so I'm surprised it hasn't been already reported.

The error shown is `different prefix: "/" and "."`

The full stack trace is:

```
/Users/srdjan/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/pathname.rb:508:in `relative_path_from'
devise (4.1.0) lib/devise/failure_app.rb:59:in `recall'
devise (4.1.0) lib/devise/failure_app.rb:39:in `respond'
actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
org/jruby/RubyProc.java:318:in `call'
devise (4.1.0) lib/devise/failure_app.rb:21:in `call'
devise (4.1.0) lib/devise/delegator.rb:5:in `call'
warden (1.2.6) lib/warden/manager.rb:142:in `call_failure_app'
warden (1.2.6) lib/warden/manager.rb:128:in `process_unauthenticated'
warden (1.2.6) lib/warden/manager.rb:43:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/application.rb:165:in `call'
org/jruby/RubyKernel.java:1823:in `public_send'
railties (4.2.6) lib/rails/railtie.rb:194:in `method_missing'
```

It's extremely easy to reproduce.
1. With current release of Devise and JRuby, create a Rails app
2. Add log in logic using Devise defaults
3. Try to log in with invalid credentials

Currently, the workaround is to lock into a known good version of Devise. For my app, that's 3.4.1.

**Comment by trejkaz** [comment] 2016-07-04 03:34
I get this exact same error with Ruby 2.3.1 so I'm not sure this is a JRuby-only thing.

**Comment by evertonts** [comment] 2017-01-18 17:48
@batasrki @trejkaz Any news on this issue?

**Comment by btazi** [comment] 2017-11-09 17:06
I have the same problem , I tried with ruby 2.2.6, ruby 2.3.3 and ruby 2.4.1
Any idea ? https://stackoverflow.com/questions/47206273/different-prefix-and-http-localhost3000-with-devise

**Comment by tegon** [comment] 2018-03-30 17:28
@btazi Can you provide us a sample application that reproduces the issue in isolation?
You can also use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-05-08 21:38
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-05-08 21:38 UTC
Labels: Bug, Needs more info
