### ISSUE TITLE
Confirmation message not always displayed after sign up

### ISSUE THREAD

**Issue by BM5k** [plataformatec/devise#3507] opened 2015-03-09 22:05 UTC
We have a [spec][1] that goes through our sign up process and checks to make sure the `devise.registrations.signed_up_but_unconfirmed` message is displayed.

This test has started to occasionally fail. Instead of the expected message, `devise.registrations.signed_up` is displayed.

Checking in the database when this happens, there’s only a single unconfirmed user. 

I’m at a loss for how to troubleshoot. There are a lot of pieces in place here: rails, capybara, rspec. Because of the seemingly random nature, I’m not sure I can provide a smaller codebase that reproduces the issue.

rails-4.2.0
devise-3.4.1
capybara-2.4.4
rspec-rails-3.2.1

[1]: https://github.com/meeples/meeples/blob/master/spec/features/users_spec.rb#L18-L32

**Comment by josevalim** [comment] 2015-03-09 22:11
It there any javascript involved for showing the message? It feels more like it is a timing issue somewhere than Devise fault.

**Comment by BM5k** [comment] 2015-03-09 22:19
@josevalim there’s not any js involved. 

(I removed the phantomjs & poltergeist info from the issue after I verified that this test doesn’t actually use them anyway. Got a little carried away thinking about dependencies that _could_ be causing trouble.)

**Comment by nashby** [comment] 2015-03-15 13:52
@BM5k hey, I think the problem is [here](https://github.com/meeples/meeples/blob/d5288fca730f39e094f3ff6a1e06dc2e01af0af6/spec/features/plays_spec.rb#L110). Since you never call `Timecop.return` after that freeze your time is messed up and that causes Devise's logic [here](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L188) to work incorrectly.

**Comment by BM5k** [comment] 2015-03-15 22:44
@nashby D'oh! That's a great find. I'll add in a `Timecop.return` and see if that fixes our issue.

**Comment by nashby** [comment] 2015-03-16 11:02
@BM5k cool, I'll close it for now. Feel free to ping me if it's not fixed.

**Closed by nashby** 2015-03-16 11:02 UTC
