### ISSUE TITLE
Use recall but not redirect for not confirmed users

### ISSUE THREAD

**Issue by printercu** [plataformatec/devise#4567] opened 2017-06-21 08:59 UTC
Hi!

I've found that behaviour differs when signing-in with invalid params or with locked account and when account is waiting to be confirmed. In first to cases it uses `:recall` strategy for warden and renders page immediately. But in last one it performs redirect.

I've tried to change `activatable` hook and pass `recall` to throw, but it seems to try authorize user again when rendering `new`.

Why does not `Models::Confirmable` define `#valid_for_authentication?` same way `Lockable` does it? Should it be fixed?

**Comment by tegon** [comment] 2017-12-22 18:40
Hello @printercu, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:29
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-11 20:29 UTC
Labels: Needs more info
