### ISSUE TITLE
Override confirmations so users can pick their own passwords as part of confirmation activation v. 4?

### ISSUE THREAD

**Issue by chevinbrown** [plataformatec/devise#4075] opened 2016-04-30 05:35 UTC
Followed the wiki perfectly, but in version 4, I continue to get "Confirmation token can't be blank", but according to my log, it is being patched to the correct route#method

Rails 5 possibly is posting params as a hash? So posted params are `user:{ password:...token:...}`

Please advise on confirmation update method for v. 4.0.1 and Rails 5.

**Comment by ulissesalmeida** [comment] 2016-05-01 15:38
@chevinbrown Hey, thank you for your report, it looks strange. I would like to further investigate it.
It would be helpful if you provide more information. Like, for example, a sample application or a test case that reproduces the error.

Best

**Comment by Startouf** [comment] 2016-06-12 00:48
I have added password confirmation following the wiki [here](https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation) with Rails 5, it seems to work ?

Here is my (slightly modified) code if it can help

```
 def update
    with_unconfirmed_confirmable do
      if @confirmable.must_change_password?
        @confirmable.attempt_set_password(params[:user])
        if  @confirmable.valid? and
            @confirmable.password == @confirmable.password_confirmation
          do_confirm
        else
          do_show
          @confirmable.errors.clear #so that we wont render :new
        end
      else
        @confirmable.errors.add(:email, :password_already_set)
      end
    end

    if @confirmable.errors.any?
      self.resource = @confirmable
      render 'devise/confirmations/new' #Change this if you don't have the views on default path
    end
  end

def with_unconfirmed_confirmable
    @confirmable = User.find_or_initialize_with_error_by(:confirmation_token, params[:confirmation_token])
    self.resource = @confirmable
    if not @confirmable.new_record?
      @confirmable.only_if_unconfirmed {yield}
    end
  end
```

**Comment by vokshirg** [comment] 2016-07-26 09:05
Hi) I've tried use instruction from  [here](https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation) v3.5.2 but I'm using devise v4.2 and it seems doesn't work
Rails 4.2.7

**Comment by gbrl** [comment] 2016-10-06 15:53
I followed the instructions as well, and I get a validation error: "Password can't be blank"

**Comment by tegon** [comment] 2017-12-23 16:31
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-23 16:31 UTC
Labels: Bug, Needs more info
