### ISSUE TITLE
Lockable for a never signed in user do not work

### ISSUE THREAD

**Issue by Rovel** [plataformatec/devise#4498] opened 2017-04-17 19:42 UTC
Hi,

I was testing the lockable method and the lockable method did not worked when a user never signed in. Is that meant to be?

**Comment by aptituz** [comment] 2017-05-09 17:13
@Rovel Do you use devise in conjunction with a provider like LDAP?

I think this one is a quiet fundamental issue which occurs only when the list of existing users is (at first) unknown to the application, e.g. when authenticating against a company LDAP server.

In our case we are using devise in conjunction with the ldap authenticable gem as the *only* authentication strategy.

The problem with this is: the row in the users table is created when authentication succeeds, e.g. after a successful bind to the LDAP server. Thus the failed tries are not tracked at all.

There are some ways to solve it:
* in the application: prepopulate the database with the existing users and update them regulary
* in devise: create a user record after checking with the authentication strategy weither it exists (but with providers like LDAP that probably means to bind with an admin DN)

Creating user records on first try or tracking tries independently should probably be avoided to not fillup the database.

**Comment by Rovel** [comment] 2017-05-09 19:58
Actually I don't use LDAP, but I can if necessary.

My thing is that a user don't register itself, a admin do it for him, in
this case the time between the user creation and the first sign-in, the
lockable don't track the failed attempts...

So I don't have problems with dummy users or managing unwanted users.

I don't know if this behavior extends to all devise uses since this
application is very peculiar.


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2


2017-05-09 14:13 GMT-03:00 Patrick Schönfeld <notifications@github.com>:

**Comment by aptituz** [comment] 2017-05-09 20:25
No, that wouldnt help you. I just tried to provide additional Info on what I know. We do have the same problem, but for different reasons.

Just to verify: When the user tries to login, the account has already been created by the admin? Anything special with the newly generated Account? Anything that would be different with the Devise Registration Code?

**Comment by Rovel** [comment] 2017-05-09 21:25
nops, just the regular devise......

we'r probably going to search/test what field that is filled up after the
first sign-in that unlocks the lockable feature.... but since this is not
an emergency for me right now it may take a while, so fell free to to the
same.




Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2


2017-05-09 17:25 GMT-03:00 Patrick Schönfeld <notifications@github.com>:

**Comment by tegon** [comment] 2017-12-21 20:05
Hello @Rovel, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by Rovel** [comment] 2017-12-29 19:11
Sorry for the late response, I'll provide a sample app as soon as I can.

**Comment by tegon** [comment] 2018-06-12 13:30
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-06-12 13:30 UTC
Labels: Needs more info
