### ISSUE TITLE
Devise 4.4.0 sign_in password validators

### ISSUE THREAD

**Issue by thomasgthy** [plataformatec/devise#4750] opened 2018-01-09 18:42 UTC
## Environment

- Ruby 2.4.2
- Rails 5.1.4
- Devise 4.4.0

## Current behavior
Since I upgraded to Devise 4.4.0, I've experienced issues with the lockable module. I've added this module following exactly the devise documentation. ([https://github.com/plataformatec/devise/wiki/How-To:-Add-:lockable-to-Users](url)). Then, when sign in to my application I've got following devise error messages:
* Password can't be blank
* Password confirmation can't be blank

After refreshing this page, I'm signed in as expected.
I don't really understand the devise error message as there are no password confirmation in the form or in the sign_in request and I can print the user object content when debugging and see that the password is not empty at all. It looks like I have sign_up error messages on a sign_in page.

Also, just by downgrading to Devise 4.3.0, it works just fine again with same config.

Thanks for your help.

**Comment by tegon** [comment] 2018-01-10 12:24
Possible a duplicate of #4742. What are your model validations? Are you overriding the method `password_required?`

**Comment by thomasgthy** [comment] 2018-01-10 15:25
I don't think it's the same issue than #4742. I'm not overriding `password_required?`
Also, I've figured out that removing:
* `validates :password, presence: true`
* `validates :password_confirmation, presence: true`

in my User model is kind of fixing the problem even if this is clearly not something to do. But at least it shows that the problem comes from the validators in the model.

**Comment by tegon** [comment] 2018-01-10 15:44
@thomasgthy Is there some reason to have those validations in your model instead of using the ones in the `:validatable` module?
These are virtual fields, which means that you cannot validate them unless you're creating a new user or changing an existent password.

**Comment by thomasgthy** [comment] 2018-01-10 16:30
Actually there is no specific reason. I did the devise setup a long time ago and not came back on it until this error as it was working great. I will definitely look into the validatable module but I'm still wondering where this error comes from as the Rails validators should be triggered only during User creation, save or update.
Anyway, thank you for your help @tegon

**Comment by tegon** [comment] 2018-01-10 16:44
The reason is we update the user in the trackable module, to set some fields like the sign in IP and time. This is explained at #4742

**Comment by thomasgthy** [comment] 2018-01-10 16:50
My bad, thank you for your help.

**Closed** 2018-01-10 17:18 UTC
