### ISSUE TITLE
set_reset_password_token callbacks problems

### ISSUE THREAD

**Issue by victor95pc** [plataformatec/devise#3979] opened 2016-03-01 18:13 UTC
rails (4.0.13)
devise (3.5.6)
warden (1.2.6)

Hi guys, I really like all work your guys are doing on this gem. I have a problem when sign in a user on my app, my client wants to send a reset email every time a user are signed.

So I go to app/models/user.rb, add a callback:

``` ruby
after_create :send_reset_password_instructions
```

It worked, but the user record doesn't have reset_password_token set, I search on devise's code and found a method set_reset_password_token, this method use save method in the end.

``` ruby
def set_reset_password_token
  raw, enc = Devise.token_generator.generate(self.class, :reset_password_token)

  self.reset_password_token   = enc
  self.reset_password_sent_at = Time.now.utc
  self.save(validate: false)
  raw
end
```

And when you are in a after_create callback, the save method won't work, plus every time you call save method it will trigger all callbacks, my workaround was doing like this

``` ruby
def set_reset_password_token
    raw, enc = Devise.token_generator.generate(self.class, :reset_password_token)
    update_columns(reset_password_token: enc, reset_password_sent_at: Time.now.utc)
    raw
end
```

It will improve the performance, because is going direct to the database withdraw any validations and callbacks, plus solve my problem.

So what you guys think, it's a good idea?

**Comment by alexQueue** [comment] 2016-03-02 22:39
I'm hitting this same issue, so I'll second that it's a problem that should be addressed, and I agree that `update_columns` is better than `save(validate: false)`

**Comment by alexQueue** [comment] 2016-03-02 23:20
Is it because `save` "won't work" in an `afte_create`, or because the `save` will trigger the `before_update` callback that resets the token?

**Comment by victor95pc** [comment] 2016-03-03 00:15
I need to make some test but, yes the save method do not save the record, maybe it have something with ActiveRecord, or it needs to reload the instance, I think the last one probably right, but I still think is a good idea do use update_columns in this case.

**Comment by mwesigwa** [comment] 2016-04-07 17:25
:+1:

**Comment by ulissesalmeida** [comment] 2016-04-19 18:28
@victor95pc Thank you for your report.

I agree that approach reduces the side effects and can be useful to use in your own custom callbacks. 

But at the same time, I think we can't change the method since some users may be relying on the side effects of this method , like calling callbacks, updating the `update_at` column. Some user of the gem may be loading the record and calling the method from a controlIer for example. If we change it, we breaking the behavior for a lot of people.

What we can do, maybe add a reusable method that you can do stuff without saving the record. Then you can call the method and save any way you want.

**Comment by kevinmtrowbridge** [comment] 2016-07-11 17:06
Hello,

I had this exact same problem.  Here is how I solved the issue:

```
      # NB -- fixed bug in this area: https://github.com/plataformatec/devise/issues/3979
      before_create :welcome_new_user_and_invite_to_set_password

      def welcome_new_user_and_invite_to_set_password
        if !Rails.env.test?
          raw, enc = Devise.token_generator.generate(self.class, :reset_password_token)

          self.reset_password_token = enc
          self.reset_password_sent_at = Time.now.utc

          self.send_reset_password_instructions_notification(raw)
        end
      end
```

`before_create` is after validations, so, although this is before the actual save, I believe it's nearly certain the record will make it into the database at this point.  No saving is necessary as this piggybacks the save onto the in-process create.

**Comment by tegon** [comment] 2017-12-23 15:38
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-23 15:38 UTC
Labels: Discussion

**Comment by darthwiz** [comment] 2018-06-29 13:12
I incurred into the same issue as well, and for what it's worth it was caused by `self.save(validate: false)`. 

Here's the situation: I was implementing a “force password change for new user”, so I had the following code after creation:

```ruby
    new_password = SecureRandom.hex
    user.reset_password(new_password, new_password)
    user.send_reset_password_instructions
```

I also had a complexity regexp check on the password field that required at least one uppercase, at leas one lowercase and one digit character, so the new random password was _failing_ the check. The strange thing that happened is that the password _was_ getting updated, but not the `reset_password` fields. As soon as I set a valid password by adding extra uppercase characters, my problem was solved.
