### ISSUE TITLE
localizing confirmed_at field causes the need for the user to click the confirmation_link twice

### ISSUE THREAD

**Issue by abnud1** [plataformatec/devise#3848] opened 2015-12-10 21:13 UTC
I'm using devise 3.5.3 with Rails 4.2.5 and mongoid 5,mongo 2.2 and bson 4(but I had the issue with bson 3 and mongo 2.1 though).  

From my logs I see that when I go to email preview , click the confirmation email, and then click the confirmation link, it seems that devise updates the document by setting confirmed_at to {}. 

This causes the user to see "you need to confirm your account in order to login" when he/she tries to login despite the success of the confirmation.  

Now when clicking the confirmation link again devise updates the document in the database with confirmed_at set to the correct time and the user can sign in.  

The time confirmed_at field is localized and that is why I think this happens, devise first sets confirmed_at to an empty hash and then set the time for the corresponding locale.  

I think a workaround for this is to either remove localize: true or initialize the model and set confirmed_at to {} on application start.

**Comment by josevalim** [comment] 2015-12-10 22:53
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by josevalim** [comment] 2015-12-10 22:53
Sorry about this, I've clicked the wrong button. Instead, I wanted to ask if you can please provide an application that reproduces the error?

**Comment by abnud1** [comment] 2015-12-19 15:34
to reproduce the issue:
1-create new Rails app with --skipactiverecord option
2-configure rails to use mongoid 
3-generate devise model(example User) with database_authenticatable,registrable,confirmable.  
4-generate the corresponding controllers and views for the model.
5-make confirmed_at field localized.
6-generate Mailer with rails g mailer(let's call it UsersMailer).
7-make the mailer inherits Devise's mailer.
8-define function confirmation_instructions in the mailer preview and put this in it :
    user=User.first
    UsersMailer.confirmation_instructions(user,user.confirmation_token , {})
9-run the application(rails server), register a user,go to localhost:3000/rails/mailers and click on confirmation_instructions link.  
10-click the confirmation link.  

if you followed these steps you should see "confirmation done" but when you try to sign in it says "you need to confirm your account first", if you go to rails/mailers clicked confirmation_instructions and clicked the link again you can sign in successfully.  

this doesn't happen when you don't localize confirmed_at field.

**Comment by evertonts** [comment] 2017-01-18 17:37
Can you please provide a sample application that reproduces the error?

**Comment by evertonts** [comment] 2017-01-18 17:41
@abnud1 Any news on this issue?

**Comment by tegon** [comment] 2017-12-06 23:57
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!

**Closed by tegon** 2017-12-06 23:57 UTC
