### ISSUE TITLE
migration doesn end with rb

### ISSUE THREAD

**Issue by cvandermeer** [plataformatec/devise#3511] opened 2015-03-11 13:09 UTC
the migraton file when generating a devise model doesnt end with rb so it doesnt get migrated.

**Comment by lucasmazza** [comment] 2015-03-11 13:12
Duplicate of #3272. If not, please provide more information about your app, which Devise version you are using and a repository that reproduces the error.

**Closed by lucasmazza** 2015-03-11 13:12 UTC
