### ISSUE TITLE
undefined method `encrypted_password=' for User

### ISSUE THREAD

**Issue by warpling** [plataformatec/devise#3527] opened 2015-03-20 19:24 UTC
I've been unable to figure this one out with my team, and was hoping someone here may be able to help us or give us some troubleshoot pointers! We're using Rails 4.0.2 and Mongoid 4.0.2 (see `Gemfile.lock`). I've seen issues #589 and #2656 and tried the methods therein but the problem persists.

* `rake db:reset` throws the same ````NoMethodError: undefined method `encrypted_password=' for #<User:0x007fe1470e03a0>````
* `User.new.respond_to?(:encrypted_password=)` returns `true`

Gemfile.lock + backtrace: https://gist.github.com/warpling/4bd2b59b65df190c3ed1

**Comment by nashby** [comment] 2015-03-22 08:47
@warpling do you have `:encrypted_password` field in your user document?

**Comment by warpling** [comment] 2015-03-22 09:05
Yep!
```
class User
  include Mongoid::Document
  has_one :token, dependent: :delete
  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  # ...
```

**Comment by nashby** [comment] 2015-03-22 09:18
Can you please provide a sample application that reproduces the error?

**Comment by warpling** [comment] 2015-03-22 09:29
Let me know if this is too much to ask of you or too heavy-handed of a sample, but the project in question is the current build of [OpenFarm](https://github.com/openfarmcc/OpenFarm).
We just had a new developer join that hit this error after getting thing up and running so I'm not the only one and I think it should be easy to replicate off the bat.

Thank you for the help and quick replies @nashby! :bow:

**Comment by nashby** [comment] 2015-03-22 12:54
@warpling just tried to setup this application and looks like everything work ok for me. I was able to sign in successfully. Any idea how I can reproduce it?

**Comment by simonv3** [comment] 2015-03-23 01:42
@nashby, thanks for putting so much effort into trying to replicate it. Do you know of any issues that might crop up with devise and a specific mongod configuration?

We first got the problem with someone else trying to install the project on a fresh install (I suspect they didn't have mongo installed to start with):

We're tracking the issue here on our own project: https://github.com/openfarmcc/OpenFarm/issues/542

**Comment by nashby** [comment] 2015-03-26 12:20
@simonv3 sorry, no idea actually. I'm going to close it for now since there's no way we can reproduce it. But feel free to ping me if you have any way how to replicate this problem in a simple app.

**Closed by nashby** 2015-03-26 12:20 UTC
