### ISSUE TITLE
"Devise::ParameterSanitizer#sign_in" method is deprecated when using Cucumber / Capybara

### ISSUE THREAD

**Issue by DannyBen** [plataformatec/devise#4048] opened 2016-04-20 14:45 UTC
Trying to upgrade to 4.0, I have cleaned most of the deprecation warnings, but my Cucumber+Capybara tests fail with a deprecation warning that I do not know where I should fix.

When running my feature tests, I get this:
```
"Devise::ParameterSanitizer#sign_in" method is deprecated and it will be removed from Devise 4.1.
Please use the `permit` method on your sanitizer `initialize` method.
```

But I do not have any "sanitizer".

The only other related place I had fixed, was in the application controller, which now looks like:
```ruby
  # applucation_controller.rb
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :phone, :language, :timezone]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
```

The full output when running my test, for context:
```
$ bin/cucumber features/audit.feature
Running via Spring preloader in process 11771
Using the default profile...

DEPRECATION WARNING: [Devise] Parameter sanitization through a "Devise::ParameterSanitizer#sign_in" method is deprecated and it will be removed from Devise 4.1.
Please use the `permit` method on your sanitizer `initialize` method.

  class Devise::ParameterSanitizer < Devise::ParameterSanitizer
    def initialize(*)
      super
      permit(:sign_in, keys: [:param1, :param2, :param3])
    end
  end
 (called from get at /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/forwardable.rb:183)
  Scenario: See a list of all audits
    Given I am logged in as "user"
      wrong number of arguments (0 for 1..2) (ArgumentError)
      ./features/step_definitions/login.rb:6:in `/^I am logged in as "(.*?)"$/'
      features/audit.feature:7:in `Given I am logged in as "user"'
    And I am on the "audits" page
    Then the page should say "Audit"
    And the page should have an ".audit" element

Failing Scenarios:
cucumber features/audit.feature:6

1 scenario (1 failed)
4 steps (1 failed, 3 skipped)
Failed
```

The complaint above, about `login.rb` line 6, refers to the `visit` line below:

```ruby
# step_definitions/login.rb
Given(/^I am logged in as "(.*?)"$/) do |user|
  visit user_session_path # <--- line 6
  fill_in 'Email', with: "#{user}@email.com"
  fill_in 'Password', with: "---snip---"
  click_on 'Sign In'
  expect(page).to have_selector '.notice'
end
```

Not sure if this is a bug, or a problem on my side, or just a slightly confusing deprecation warning, or a capybara issue.....

**Comment by DannyBen** [comment] 2016-04-20 16:50
( Adding a separate comment due to the size of the first one and the importance of this one )

I have created a new rails app, and installed a fresh Devise + Cucumber + Capybara.
The deprecation warning appears **right out of the box**, and causes capybara to fail.

I have created [this very minimal test repo][1] for anyone who wants to reproduce.

[1]: https://github.com/DannyBen/devise4-issue

**Comment by ulissesalmeida** [comment] 2016-04-20 17:59
@DannyBen Thank you for your report. I'll take a look.

**Comment by ulissesalmeida** [comment] 2016-04-20 20:49
@DannyBen 

I think in your sample repository you may have misconfigured cucumber.

To include helpers, you must use the [`World`](https://github.com/cucumber/cucumber/wiki/A-Whole-New-World) setup, not `include`. Also, that step failing because Cucumber is not providing the rails URL helpers. I think it has already a issue open for that: https://github.com/cucumber/cucumber-rails/issues/284

You can fix your sample application using this setup:

```ruby
#features/support/env.rb

module RailsUrlHelpers
  include Rails.application.routes.url_helpers
end

World(Devise::TestHelpers, RailsUrlHelpers)
```

Also in the steps, I make it pass changing some assertions and creating the user before login:
```ruby
Given("I am logged in as user") do
  User.create!(email: "user@email.com", password: "asdasdasd")

  visit new_user_session_path
  fill_in 'Email', with: "user@email.com"
  fill_in 'Password', with: "asdasdasd"
  click_on 'Log in'
  assert page.has_content?('Welcome#index'), "User must have logged in"
end
```

With the setup fixed and changes on assertion, the test is passing without any depecration warning.

**Comment by DannyBen** [comment] 2016-04-20 21:01
First, thanks - I will check it both in the test app and actual apps.
But - you should know that this exact setup is working perfectly with several other apps with Devise < 4. You can even try it in the sample app (the test will fail, but for other, trivial reasons).

Every config / include I have done here is taken from one guide or another.

So - something in Devise 4 is either changed for the worse, or at the very least, causes other (possibly fragile) things to break. I believe it requires some attention, to see if the new changes can be less "in your face" - Devise is a fundamental gem for a lot of people, and keeping up with latest versions should be as smooth and easy as possible.

**Comment by ulissesalmeida** [comment] 2016-04-20 21:27
@DannyBen Thank you for your feedback. We trying to make Devise upgrade smooth as possible, we have release candidate version of Devise 4 for several months and improving a lot with the users feedback. But of course, errors can still exist, that's why we are open to receive reports and bug fixes. We didn't release this version careless.

The sample app error is more related to Cucumber and Rails configuration than Devise itself. Sincerely, Cucumber is not my strong, we are open to receive PRs that makes both works nice.

I don't know which guide are you following, but the `Devise::TestHelpers` should be only included in ControllerTests. You can read more about it the [class itself](https://github.com/plataformatec/devise/blob/master/lib/devise/test_helpers.rb#L4). Not in Cucumber or feature tests.

That deprecation warning I think is not related to that application controller you mentioned. I think reviewing your configuration and removing "Devise::TestHelpers" of your cucumber test suite you may remove these depecration warnings.

**Comment by ulissesalmeida** [comment] 2016-04-20 22:06
@DannyBen Thank you for the update.  I think the problem is include `Devise::TestHelpers` in feature or cucumbers tests, it was designed to work with controller tests. About the Rails URL helpers may be a problem of cucumber and rails integration like mentioned in this issue: https://github.com/cucumber/cucumber-rails/issues/284

I'm closing this issue. Feel free to reopen if we have any evidence that is Devise issue. Thank you again.

**Closed by ulissesalmeida** 2016-04-20 22:06 UTC

**Comment by DannyBen** [comment] 2016-04-21 05:06
Many thanks.
