### ISSUE TITLE
4.4.0 Re renders sign in screen after successful sign in.

### ISSUE THREAD

**Issue by JonRowe** [plataformatec/devise#4746] opened 2018-01-05 23:12 UTC
## Environment

- Ruby 2.4.5
- Rails 4.2
- Devise 4.4.0

## Current behaviour

After successful sign in, the sign in screen is shown with a `must contain a number or symbol` error message for password, despite password containing number and symbol, and despite user being signed in.

## Expected behaviour

User is redirected to admin root.

**Comment by JonRowe** [comment] 2018-01-06 00:16
This appears to be caused by a custom validation on my end, which is run and not cleared when the user is logged in.

**Comment by tegon** [comment] 2018-01-08 16:24
Duplicate of #4742

**Closed by tegon** 2018-01-08 16:24 UTC
