### ISSUE TITLE
Devise syntax errors in ruby 2.5.0

### ISSUE THREAD

**Issue by vincentwoo** [plataformatec/devise#4739] opened 2017-12-28 00:57 UTC
## Environment

- Ruby 2.5.0
- Rails 5.x
- Devise 4.3.0

## Current behavior

Starting a Rails server with ruby 2.5.0 yields these syntax errors:

```
[36171] ! Unable to load application: SyntaxError: /Users/vwoo/.gem/ruby/2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '{', expecting keyword_end
...ion only: [:create, :destroy] { request.env["devise.skip_tim...
...                              ^
/Users/vwoo/.gem/ruby/2.5.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '}', expecting keyword_end
..."devise.skip_timeout"] = true }
...
```

## Expected behavior

The app starts normally

**Comment by vincentwoo** [comment] 2017-12-28 01:03
Oh, this is apparently fixed with https://github.com/plataformatec/devise/commit/1009096172f2cbc86bcd54d053c89a09be67fb9f.

Can we get a release?

**Comment by redtachyons** [comment] 2017-12-28 03:09
Duplicate of #4738 , #4736, #4719, #4703 . Devise is currently not compatible with latest stable version of ruby

**Comment by rusterholz** [comment] 2017-12-28 18:11
@tegon @carlosantoniodasilva @rafaelfranca Since the change is already on master, what is the expected timeframe for releasing this?

**Comment by tegon** [comment] 2017-12-29 20:02
Hi everyone, sorry for the delay. I had a lot of work to do lately. I was only able to work on this today. Anyway, version [4.4.0](https://rubygems.org/gems/devise/versions/4.4.0) is out.

Thanks

**Closed by tegon** 2017-12-29 20:02 UTC
