### ISSUE TITLE
NoMethodError: undefined method `will_save_change_to_email?`

### ISSUE THREAD

**Issue by LucBRG** [plataformatec/devise#4740] opened 2017-12-28 20:53 UTC
https://github.com/plataformatec/devise/issues/4531

I've still that error, how to fix that correctly? 

ruby 2.4.1 ; Rails 5.1.4 ; Devise 4.3 ; Mongoid 6.1.0

Thank you

**Comment by tegon** [comment] 2017-12-29 20:17
Duplicate of #4542

**Closed by tegon** 2017-12-29 20:17 UTC
