### ISSUE TITLE
EOFError (end of file reached)

### ISSUE THREAD

**Issue by WilliamJones62** [plataformatec/devise#4699] opened 2017-11-16 21:54 UTC
I am developing a Rails app on Windows 10. I am using Rails 5.1.4, Ruby 2.3.3, and devise 4.3.0. When I try to send a recovery email I get the following error;

EOFError in Devise::PasswordsController#create
end of file reached

Rails.root: c:/Sites/forecast

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"nXrXB4yktICJg6pl5hLdB2uDBCiVbu43GRxmdedxjrVr7H9WwrQnws8kULBi4LLI2xMXXWIz8oL0/I+0uMl5WA==",
 "user"=>{"email"=>"billj@dartagnan.com"},
 "commit"=>"Send me reset password instructions"}

In config/environments/development.rb I have the following;
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.perform_deliveries = true
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.default_options = {from: 'no-reply@dartagnan.com'}
  config.action_mailer.smtp_settings = {
  address: 'smtp.gmail.com',
  port: 587,
  domain: ENV['GMAIL_DOMAIN'],
  authentication: 'plain',
  enable_starttls_auto: true,
  user_name: ENV['GMAIL_USERNAME'],
  password: ENV['GMAIL_PASSWORD']
  }
  config.action_mailer.perform_caching = false
  config.action_mailer.default_url_options = { :host => 'localhost:3000' }

I have done a lot of google searches but can't find a solution to this problem. Any help you can give will be greatly appreciated.

**Comment by rafaelfranca** [comment] 2017-11-22 21:47
Can you provide the full stack trace so we can see where the problem is happening?

**Comment by tegon** [comment] 2017-12-29 20:20
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-29 20:20 UTC
Labels: Needs more info

**Comment by atul-shimpi** [comment] 2018-01-13 07:16
I am facing this

**Comment by atul-shimpi** [comment] 2018-01-13 07:17
Rails - 4.2.1
Ruby 2.2.0p0

**Comment by chinna2580** [comment] 2020-08-31 14:50
still facing the same issue
`

/usr/local/lib/ruby/2.6.0/net/protocol.rb:225→ rbuf_fill
--
/usr/local/lib/ruby/2.6.0/net/protocol.rb:191→ readuntil
/usr/local/lib/ruby/2.6.0/net/protocol.rb:201→ readline
/usr/local/lib/ruby/2.6.0/net/smtp.rb:950→ recv_response
/usr/local/lib/ruby/2.6.0/net/smtp.rb:553→ block in do_start
/usr/local/lib/ruby/2.6.0/net/smtp.rb:960→ critical
/usr/local/lib/ruby/2.6.0/net/smtp.rb:553→ do_start
/usr/local/lib/ruby/2.6.0/net/smtp.rb:518→ start
/GEM_ROOT/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109→ start_smtp_session
/GEM_ROOT/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100→ deliver!
/GEM_ROOT/gems/mail-2.7.1/lib/mail/message.rb:2159→ do_delivery
/GEM_ROOT/gems/mail-2.7.1/lib/mail/message.rb:260→ block in deliver
/GEM_ROOT/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:560→ block in deliver_mail
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168→ block in instrument
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23→ instrument
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168→ instrument
/GEM_ROOT/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:558→ deliver_mail
/GEM_ROOT/gems/mail-2.7.1/lib/mail/message.rb:260→ deliver
/GEM_ROOT/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:114→ block in deliver_now
/GEM_ROOT/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:17→ handle_exceptions
/GEM_ROOT/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:113→ deliver_now
/GEM_ROOT/gems/devise-4.6.2/lib/devise/models/authenticatable.rb:200→ send_devise_notification
/GEM_ROOT/gems/devise_token_auth-1.1.0/app/models/devise_token_auth/concerns/user.rb:73→ send_reset_password_instructions
/PROJECT_ROOT/app/controllers/auth/passwords_controller.rb:28→ create
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6→ send_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194→ process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30→ process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42→ block in process_action
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132→ run_callbacks
/GEM_ROOT/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41→ process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22→ process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34→ block in process_action
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168→ block in instrument
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23→ instrument
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168→ instrument
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32→ process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256→ process_action
/GEM_ROOT/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24→ process_action
/GEM_ROOT/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134→ process
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191→ dispatch
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252→ dispatch
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52→ dispatch
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34→ serve
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:18→ block in <class:Constraints>
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:48→ serve
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52→ block in serve
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35→ each
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35→ serve
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840→ call
/GEM_ROOT/gems/warden-1.2.8/lib/warden/manager.rb:36→ block in call
/GEM_ROOT/gems/warden-1.2.8/lib/warden/manager.rb:34→ catch
/GEM_ROOT/gems/warden-1.2.8/lib/warden/manager.rb:34→ call
/GEM_ROOT/gems/rack-2.0.7/lib/rack/etag.rb:25→ call
/GEM_ROOT/gems/rack-2.0.7/lib/rack/conditional_get.rb:38→ call
/GEM_ROOT/gems/rack-2.0.7/lib/rack/head.rb:12→ call
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28→ block in call
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98→ run_callbacks
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26→ call
/GEM_ROOT/gems/airbrake-10.0.1/lib/airbrake/rack/middleware.rb:34→ call!
/GEM_ROOT/gems/airbrake-10.0.1/lib/airbrake/rack/middleware.rb:23→ call
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61→ call
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33→ call
/GEM_ROOT/gems/railties-5.2.3/lib/rails/rack/logger.rb:38→ call_app
/GEM_ROOT/gems/railties-5.2.3/lib/rails/rack/logger.rb:26→ block in call
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71→ block in tagged
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28→ tagged
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71→ tagged
/GEM_ROOT/gems/railties-5.2.3/lib/rails/rack/logger.rb:26→ call
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81→ call
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27→ call
/GEM_ROOT/gems/rack-2.0.7/lib/rack/runtime.rb:22→ call
/GEM_ROOT/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29→ call
/GEM_ROOT/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14→ call
/GEM_ROOT/gems/rack-2.0.7/lib/rack/sendfile.rb:111→ call
/GEM_ROOT/gems/rack-cors-1.0.3/lib/rack/cors.rb:95→ call
/GEM_ROOT/gems/railties-5.2.3/lib/rails/engine.rb:524→ call
/GEM_ROOT/gems/puma-3.12.1/lib/puma/configuration.rb:227→ call

/GEM_ROOT/gems/puma-3.12.1/lib/puma/server.rb:660→ handle_request
/GEM_ROOT/gems/puma-3.12.1/lib/puma/server.rb:474→ process_client
/GEM_ROOT/gems/puma-3.12.1/lib/puma/server.rb:334→ block in run
/GEM_ROOT/gems/puma-3.12.1/lib/puma/thread_pool.rb:135→ block in spawn_thread

`

**Comment by carlosantoniodasilva** [comment] 2020-08-31 15:07
@chinna2580 this appears to be an issue sending the email, in other words, happening around the underlying SMTP code talking to your external SMTP provider. There's not much devise can do about that, trying again in such cases is probably the best option, in which case I'd recommend always delivering emails in a background job of some sort that can be more easily retried.

**Comment by chinna2580** [comment] 2020-08-31 15:10
> @chinna2580 this appears to be an issue sending the email, in other words, happening around the underlying SMTP code talking to your external SMTP provider. There's not much devise can do about that, trying again in such cases is probably the best option, in which case I'd recommend always delivering emails in a background job of some sort that can be more easily retried.

but it works fine in my local server, it throws this error only in the production

**Comment by carlosantoniodasilva** [comment] 2020-08-31 17:26
@chinna2580 This will be very dependent on your dev vs prod configuration, your server vs the service you're using to send the emails, etc. If you're able to share some of that config I might be able to provide more insight, but I'd suggest you try sending other emails (non-devise related) via your production server and you should see the same problem, to help you diagnose; and also try simulating your production configuration locally in your dev environment, to try sending emails there too.

Devise is is only responsible to setup/trigger the email, not actually delivering them, that's up to the underlying library/provider. You need to have proper SMTP (or similar) configurations in place for it to work. I suggest taking a look at the Action Mailer guide & configuration options for more info: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration

**Comment by chinna2580** [comment] 2020-09-01 04:45
other emails are working fine, i mean normal email via action mailer are being sent without any issue, only the device emails are not being sent

**Comment by chinna2580** [comment] 2020-09-01 04:46
> @chinna2580 This will be very dependent on your dev vs prod configuration, your server vs the service you're using to send the emails, etc. If you're able to share some of that config I might be able to provide more insight, but I'd suggest you try sending other emails (non-devise related) via your production server and you should see the same problem, to help you diagnose; and also try simulating your production configuration locally in your dev environment, to try sending emails there too.
> 
> Devise is is only responsible to setup/trigger the email, not actually delivering them, that's up to the underlying library/provider. You need to have proper SMTP (or similar) configurations in place for it to work. I suggest taking a look at the Action Mailer guide & configuration options for more info: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration

@cantoniodasilva other emails are working fine, i mean normal email via action mailer are being sent without any issue, only the device emails are not being sent

**Comment by carlosantoniodasilva** [comment] 2020-09-01 12:01
@chinna2580 If you can code / a sample app reproducing the problem, we might be able to help diagnose further, otherwise there's not much else I can do to help, since I've never seen this one myself (and I have devise setup and working on production apps).

**Comment by asolab** [comment] 2022-09-27 07:20
@carlosantoniodasilva sorry I have related similar issues, I will need your assistance 
https://stackoverflow.com/questions/73735456/netsmtpserverbusy-in-devisepasswordscontrollercreate-in-rails-7-421-serve
