### ISSUE TITLE
Microsoft Edge, devise not working 401 not authorized

### ISSUE THREAD

**Issue by Rubytastic2** [plataformatec/devise#4360] opened 2016-11-22 17:49 UTC
Whenever using M$ Edge browser login does not work, it throws a 401.
Just regular devise and simple_Form forms with no jquery at all (disabled for now )

It works fine in Internet Exploder

Only Edge is causing problems. 
Is this a known issue or has anyone came across this?

**Comment by evertonts** [comment] 2017-01-20 10:39
Can you please provide a sample application that reproduces the error?

**Comment by clownf** [comment] 2017-05-12 09:56
I also have this problem, and now I have to write my own user authentication system

**Comment by tegon** [comment] 2017-12-20 02:34
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!

**Closed by tegon** 2017-12-20 02:34 UTC
