### ISSUE TITLE
"Undefined method `concat'" on "devise_parameter_sanitizer.permit"

### ISSUE THREAD

**Issue by marianatuma** [plataformatec/devise#4477] opened 2017-03-24 19:54 UTC
```
Failure/Error: devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :password, :password_confirmation, :cnpj, :razao_social, :nome_fantasia, :email, :tipo_entidade_id])
     
     NoMethodError:
       undefined method `concat' for #<Proc:0x0055ca9fb2d850>
       Did you mean?  concern

```
I'm using Rspec to test a custom RegistrationsController, and I haven't written a view yet, so I haven't tested this outside Rspec.

The full controller:

```
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # POST /resource
  def create
    user_params     = sign_up_params[:user_params]
    entidade_params = sign_up_params[:entidade_params]

    if !(User.exists?(email: user_params[:email]) || Entidade.exists?(cnpj: entidade_params[:cnpj]))
      @entidade = Entidade.new(entidade_params)
      @entidade.data_validade = 30.days.from_now
      
      if @entidade.save
        @user = User.new(user_params)
        @user.entidade_id = @entidade.id
        if @user.save
          flash[:notice] = 'Usuario criado com sucesso.'
          redirect_to root_path
        end
      end
    end
  end
  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :password, :password_confirmation, :cnpj, :razao_social, :nome_fantasia, :email, :tipo_entidade_id])
  end
end
```

Am I doing something wrong?

Edit: just tested manually, error also happens.

**Comment by JustLey** [comment] 2017-03-25 04:37
This looks like a deprecation error. What Rails version are you using?

**Comment by marianatuma** [comment] 2017-03-27 12:47
Rails is on 4.2.1, Ruby is on version 2.3.1p112 and devise is also on 4.2.1.

Sorry I took so long to reply!

**Comment by JustLey** [comment] 2017-04-09 19:31
I think I see the problem. The action that should be passed must be the action your controller is trying to execute, which, in your case, is 'create'. From lib/devise/parameter_sanitize:84 :
    # * +action+ - A +Symbol+ with the action that the controller is
    #   performing, like +sign_up+, +sign_in+, etc. 

So I suggest you change the :sign_up symbol for :create, or the action name to 'sign_up' (since you are overwriting the RegistrationsController) and see where it goes.

Remember that you can call 'super' if you need only to append some logic to the existing RegistrationsController#sign_up action. So, another alternative would be to change the action name to 'sign_up', check what Devise is already doing for you and complementing it with your own logic + a 'super' call for the ancestor method.

I hope my comment helps :D also, sorry for the delayed response, pretty busy lately.

**Comment by tegon** [comment] 2017-12-22 13:17
Hello @marianatuma, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:28
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Comment by jerome-diver** [comment] 2018-11-18 07:50
@marianatuma did you find a solution ?
@tegon i have the same problem.
Rails-5.2.1 installed with ruby-2.5.1

My initial state is to have an empty user table inside my database (no user registred)... i want to create one by sign_up. I added some columns in my database (username, family_name, second_name), then add them to this method "signup_params" inside app/controller/users/registrations_controller.rb file (i understand that it is the way to add these parameters to be valid with the other original ones from default devise one's).
And get the same error.

I think that 'concat' is call from somewhere for add (concat) these 3 entries to the default one to be "white-listed". These entry are ":username, :family_name, :second_name". I tryed with 'username', 'family_name', 'second_name' but same result.

I hope @marianatuma (if she find) to be able to share and help with this, or maybe someone other has an idea ?

thank you for your help.

**Comment by tegon** [comment] 2018-12-27 11:38
I'm closing this issue because it had no recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-12-27 11:38 UTC
Labels: Needs more info

**Comment by jerome-diver** [comment] 2018-12-27 21:38
yes, i'm still facing the same problem.
something wrong never resolved staying there... don't close before resolve please.

**Comment by tegon** [comment] 2018-12-28 11:51
@jerome-diver Did you see the test app I sent you? I wasn't able to reproduce the issue, so I've asked for a sample application that does so I can see what's happening, but I didn't get any response, that's why I closed the issue.

**Comment by jerome-diver** [comment] 2018-12-28 14:16
oh yes, sorry.
Well, i can give you my open code (it is a test application anyway). You can try it and see.
That's strange because i don't know where the problem is from (so difficult for me to create a specific test case only for this problem, i think if i could do it i done it).
[my bitbucket open source code](https://bitbucket.org/jerome___/aquaworks/src/master/)

**Comment by tegon** [comment] 2018-12-28 18:02
@jerome-diver I took a look at your code and it turns out there are a couple of changes to be done in order for this to work:

First, you're calling `Devise::ParameterSanitizer#permit` two times for the same action (`:sign_up`): in [`ApplicationController`](https://bitbucket.org/jerome___/aquaworks/src/76872001ac0c2a8bdf40d3dafeb0a63f0c8d18d3/app/controllers/application_controller.rb#lines-15) and in [`Users::RegistrationsController`](https://bitbucket.org/jerome___/aquaworks/src/76872001ac0c2a8bdf40d3dafeb0a63f0c8d18d3/app/controllers/users/registrations_controller.rb#lines-40). This is unnecessary - and it's also what's causing the issue.

There are basically two ways to permit a list of keys using `Devise::ParameterSanitizer#permit`: using the `keys` parameter or by passing a block. Internally, the attributes are kept in a [hash of arrays](https://github.com/plataformatec/devise/blob/40f02ae69baf7e9b0449aaab2aba0d0e166f77a3/lib/devise/parameter_sanitizer.rb#L48), with one key for each action: `sign_in,` `sign_up` and `account_update`. The default looks like this:
```ruby
{:sign_in=>[:login, :password, :remember_me], :sign_up=>[:password, :password_confirmation], :account_update=>[:login, :password, :password_confirmation, :current_password]}
```

Your application is first passing a block - in `ApplicationController` - and later trying to add more attributes using the `keys` parameter - in `Users::RegistrationsController`. 
So what happens is that in the second call, Devise tries to add keys to a `Proc`.
```ruby
# app/controllers/application_controller.rb

devise_parameter_sanitizer.permit(:sign_up) { |p| p.permit(:username, :familly_name, :second_name, :email, :password, :password_confirmation) }

# @permitted[:sign_up] is now a Proc
<Proc:0x00007f9f9ff24630@/Users/tegon/src/public/aquaworks/app/controllers/application_controller.rb:15>

# app/controllers/users/registrations_controller.rb
devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :familly_name, :second_name])

@permitted[:sign_up].concat([:username, :familly_name, :second_name]) # error
```

So basically what you have to do is remove one of the calls - I'd say to remove the `ApplicationController` one since this is a responsibility of `Users::RegistrationsController`.  But if you go with that option, you'll have to rename the methods [`sign_up_params`](https://bitbucket.org/jerome___/aquaworks/src/76872001ac0c2a8bdf40d3dafeb0a63f0c8d18d3/app/controllers/users/registrations_controller.rb#lines-39) and [`account_update_params`](https://bitbucket.org/jerome___/aquaworks/src/76872001ac0c2a8bdf40d3dafeb0a63f0c8d18d3/app/controllers/users/registrations_controller.rb#lines-44). They [exist](https://github.com/plataformatec/devise/blob/40f02ae69baf7e9b0449aaab2aba0d0e166f77a3/app/controllers/devise/registrations_controller.rb#L139) in the [superclass](https://github.com/plataformatec/devise/blob/40f02ae69baf7e9b0449aaab2aba0d0e166f77a3/app/controllers/devise/registrations_controller.rb#L143) `Devise::RegistrationsController` and overriding cause issues. I suggest you rename them to `configure_sign_up_params` and `configure_ account_update_params`.

I hope this helps.

**Comment by jerome-diver** [comment] 2018-12-28 18:51
@tegon i just read your explication and this make sens, i understand (you explication is perfect also). Fantastic, i'm very happy because i was stick on that for long time now and really, you take time to explain clearly what"s happening.

Tomorrow i will correct my errors.

Thank you very much for your great and useful help @tegon.
