### ISSUE TITLE
The dynamically changing state of `user_signed_in?`

### ISSUE THREAD

**Issue by NuclearMachine** [plataformatec/devise#4501] opened 2017-04-21 16:27 UTC
Sometimes my views will not detect `user_signed_in?` and give me an undefined method.   I have to turn off my server and re-add  `devise_for :users` to my routes and start the server. Then I will have to again turn off my server and remove  `devise_for :users`  from my routes , turn my server on, so that rails can "detect" `user_signed_in?`. Is this a bug?

My routes: 
```
Rails.application.routes.draw do
  
  root 'main_pages#home'

  devise_for :users# <---- will have to re-add this when the bug appears and remove it

  devise_scope :user do
  	get '/signup', to: 'users/registrations#new'
  	post '/signup', to: 'users/registrations#create'
  	get '/login', to: 'users/sessions#new'
  	post '/login', to: 'users/sessions#create'
  	delete '/logout', to: 'users/sessions#destroy'
    get '/recover', to: 'users/passwords#new'
    post '/recover', to: 'users/passwords#create'
    get '/new_password', to: 'users/passwords#edit'
    put '/new_password', to: 'users/passwords#update' 
    get '/confirmation', to: 'users/confirmations#show'   
  end
end

```

**Comment by alfie-max** [comment] 2017-04-28 09:19
Hi, i'm sure there must be something going on here, but to debug, can you share an app with reproducing just this issue?

**Comment by tegon** [comment] 2017-12-21 19:57
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-21 19:57 UTC
