### ISSUE TITLE
Rememberable config.extend_remember_period not updating cookie expiry

### ISSUE THREAD

**Issue by joecorkerton** [plataformatec/devise#4675] opened 2017-10-18 09:49 UTC
Using the current setup to test rememberable functionality:
```
config.extend_remember_period = true
config.remember_for = 1.minute
config.timeout_in = 30.seconds
```

The cookie expiry is not updating when refreshing (or closing and re opening) the page before the original expiry time (45 seconds after login)

**Comment by tegon** [comment] 2017-12-20 02:21
Hi  @joecorkerton, thank you for the report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:29
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-11 20:29 UTC
Labels: Needs more info
