### ISSUE TITLE
Confirmable with Mongoid sending multiple confirmation emails

### ISSUE THREAD

**Issue by Hitabis** [plataformatec/devise#4571] opened 2017-06-30 08:03 UTC
While using [mongoid](https://github.com/mongodb/mongoid) in conjunction with devise's _confirmable_ module I am receiving the confirmation instructions email every time I save my user object.
The confirmation link in all emails is identical and is being sent even after I have confirmed the user's email address.

**Environment**
Rails        5.1.1
Devise    4.3.0
Mongoid 6.2.0

**Comment by pnock** [comment] 2017-07-06 16:30
Take a look at https://github.com/plataformatec/devise/pull/4159 and https://github.com/plataformatec/devise/pull/4160. This may be a duplicate of those.

**Comment by tegon** [comment] 2017-11-24 16:54
@Hitabis Can you confirm if your issue is the same as the mentioned above?
Are you using the gem `mongoid-paperclip` in your project too?

**Comment by Hitabis** [comment] 2017-11-27 07:12
@tegon yes we are using `mongoid-paperclip`.

**Comment by tegon** [comment] 2017-11-27 13:06
Ok, thank you!
I'm closing this in favor of #4160.

**Closed by tegon** 2017-11-27 13:06 UTC
