### ISSUE TITLE
Unable to put a definite time interval on devise reset password

### ISSUE THREAD

**Issue by DhawalSawla** [plataformatec/devise#4481] opened 2017-03-31 19:17 UTC
Unable to use this config command. 
config.reset_password_within = 6.hours
This does not work. The user can reset his password through the link provided in the email even after 2 days.

**Comment by Talha5** [comment] 2017-03-31 19:27
where are you putting this ? should be in devlopment/production.rb

**Comment by pachonk** [comment] 2017-03-31 19:32
To specify, the devise initializer.

**Comment by DhawalSawla** [comment] 2017-04-01 00:28
Yes, I am specifying in devise.rb. But its not working.

**Comment by tegon** [comment] 2018-03-30 16:31
Hello thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
You can also use our [bug report template](https://github.com/plataformatec/devise/blob/master/guides/bug_report_templates/integration_test.rb).
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-05-08 21:40
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-05-08 21:40 UTC
Labels: Needs more info
