### ISSUE TITLE
ActionController::InvalidAuthenticityToken Load balanced

### ISSUE THREAD

**Issue by bopritchard** [plataformatec/devise#4502] opened 2017-04-21 19:06 UTC
App runs perfectly in development, what else is new. Move it load balanced test environment and things get screwy.

A POST to the load balanced (2 destinations) url will throw a

    ActionController::InvalidAuthenticityToken
error

The exact same POST to one of the balanced url by IP succeeds.

What should I be looking for? The secrets are the same on both

Thanks

Ruby 2.3.1 Rails 5.0.2 Devise 4.2.1 nginx/1.10.2

**Comment by tegon** [comment] 2017-12-21 19:56
Hello @bopritchard, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-11 20:29
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-11 20:29 UTC
Labels: Needs more info
