### ISSUE TITLE
Can't override destroy session action

### ISSUE THREAD

**Issue by zegetech** [plataformatec/devise#4723] opened 2017-12-14 15:34 UTC
## Environment

- Ruby 2.4.2
- Rails 5.1 api only
- Devise 4.3

## Current behavior

Trying to overide the sessions destroy action as i have successfully overriden create action. However, overriding destroy fails

```ruby
# route.rb
devise_for :user, skip: :all
  as :user do
    post :sign_up, to: 'auth/users/registrations#create', as: :user_registration
    post :confirmation, to: 'auth/users/confirmation#create', as: :user_confirmation
    post :sign_in, to: 'auth/users/sessions#create', as: :user_session
    delete :sign_out, to: 'auth/users/sessions#destroy', as: :destroy_user_session
  end

# Session controller
class Auth::Users::SessionsController < Devise::SessionsController
  # DELETE /sign_out
  def destroy
    render json: {'overiden': 'yes'}
  end

end
```
## Expected behavior
Should display  
```json
{
    "overiden": "yes"
}
```
currently displays
```json
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `respond_to' for #<Auth::Users::SessionsController:0x0000559a61447f68>\nDid you mean?  respond_to?\n               respond_with\n               responder\n               responder=\n               responder?>",
    "traces": {....
```
## When Hacked
If I change the `destroy` method name to `destroys`, it works as expected
That is 
```ruby
# route.rb
...
delete :sign_out, to: 'auth/users/sessions#destroys', as: :destroy_user_session
...

# Session controller
...
  def destroy
    render json: {'overiden': 'yes'}
  end
...
```

**Comment by tegon** [comment] 2017-12-20 01:48
Hi @zegetech, thank you for the report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-04 12:52
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-04 12:52 UTC
Labels: Needs more info

**Comment by marktellez** [comment] 2018-03-21 15:40
I am having this problem as well

**Comment by aalsamman** [comment] 2019-03-10 17:46
As I also had the same issue with very similar setup. The fix is as described in this StackOverflow 
https://stackoverflow.com/questions/26241357/overriding-devise-sessionscontroller-destroy
