### ISSUE TITLE
Can't login/logout in chrome

### ISSUE THREAD

**Issue by andreiglingeanu** [plataformatec/devise#4588] opened 2017-07-15 14:08 UTC
I'd like to point out that this issue is very hard to reproduce. And I was really believing that it is somehow connected with #645.

The thing is, I explicitly set `config.http_authenticatable = false` in my initializer but it didn't really helped out.

I can't see any obvious paths to follow, it just looks like Chrome is ignoring the cookies that the server is trying to set/remove via headers. When I manually clean cookies in Chrome, it works for a short amount of time then it starts to fail again.

I do have HTTP Basic Auth on some of the endpoints of the app but a lot of the people who complained about experiencing that never touched them.

And the most interesting part is that it fails _only_ in chrome. Firefox works just fine.

Thanks in advance for any idea on that one!

**Comment by tegon** [comment] 2017-12-12 23:19
Hello @andreiglingeanu, thanks for your report.
This seems really odd, can you provide us a sample application that reproduces the issue?

**Comment by tegon** [comment] 2017-12-29 20:18
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2017-12-29 20:18 UTC
Labels: Needs more info
