### ISSUE TITLE
Devise.secure_compare('', '') returns false

### ISSUE THREAD

**Issue by Nowaker** [plataformatec/devise#4441] opened 2017-02-22 22:29 UTC
```ruby
    return false if a.blank? || b.blank? || a.bytesize != b.bytesize
```

Was that really intended? It makes `Devise.secure_compare` unusable for situations with empty logins and/or passwords.

**Comment by cross-p6** [comment] 2017-10-28 22:36
What is your use case for an authentication (using secure_compare) without a username/password?

**Comment by Nowaker** [comment] 2017-10-28 22:39
Well, it's about doing an actual job. If it's to compare strings, it should do its job for edge cases like empty strings. For example, empty string should secure equal another empty string. Just that.

**Comment by Nowaker** [comment] 2017-10-28 22:40
And I can't provide a use case since it's been a year since I reported this. ;)

**Comment by tegon** [comment] 2017-11-24 15:07
@rafaelfranca Can we close this one?
I saw that we actually have a [test case for this ](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/test/devise_test.rb#L91) so I think it is the expected behavior.

**Comment by Nowaker** [comment] 2017-11-24 15:13
It doesn't make sense even if documented and unit tested. Compare is compare. Nil equals nil, blank string equals blank string.

**Comment by Nowaker** [comment] 2017-11-24 15:14
I can submit a PR if y'all agree with this.

**Comment by rafaelfranca** [comment] 2017-11-24 16:22
Since devise depends on Rails >= 4.1, I'd say we should be using `ActiveSupport:: SecurityUtils. secure_compare` as implementation of `Devise.secure_compare` https://github.com/rails/rails/blob/0cad778c2605a5204a05a9f1dbd3344e39f248d8/activesupport/lib/active_support/security_utils.rb#L11-L19.

This will change the behavior for what you expect when both strings are blank. And in Rails 5.2 this will use the `variable_size_secure_compare`.

**Comment by tegon** [comment] 2017-12-07 00:49
@Nowaker would you be willing to open a PR with this change?

**Comment by Nowaker** [comment] 2017-12-07 02:50
@tegon Absolutely.

**Comment by shrirambalakrishnan** [comment] 2017-12-17 14:34
@Nowaker are you working on this? If not, can I start working on it?

**Comment by tegon** [comment] 2018-05-09 17:50
Closed via https://github.com/plataformatec/devise/pull/4829

**Closed by tegon** 2018-05-09 17:50 UTC
Labels: PR attached
