### ISSUE TITLE
Scope with unique path leads to incorrect `signed_in_root_path`

### ISSUE THREAD

**Issue by mobilutz** [plataformatec/devise#4657] opened 2017-09-29 14:38 UTC
I have a application that has this devise route config:
```
devise_for :admins, path: :admins
[...]
namespace :admins do
  [...]
  root to: 'dashboards#show'
end
[...]
root to: 'dashboards#show'
```

This leads to these routes:
```
[...]
admins_root GET         /admins(.:format)       admins/dashboards#show
       root GET         /                       dashboards#show
[...]
```

This unfortunately does not play well with Devise, as the `signed_in_root_path` will not return the correct root path, because the DeviseMapping is not being handled correctly.

This is the `Devise.mappings` I get:
```
{:admin =>
#<Devise::Mapping:0x007fdf71412cd0
   @class_name="Admin",
   @controllers={:sessions=>"devise/sessions", :passwords=>"devise/passwords"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x007fdf71412870 @name="Admin">,
   @modules=[:database_authenticatable, :recoverable, :trackable],
   @path="admins",
   @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :password],
   @scoped_path="admins",
   @sign_out_via=:delete,
   @singular=:admin,
   @strategies=[:database_authenticatable],
   @used_helpers=[:session, :password],
   @used_routes=[:session, :password]>
}
```

Unfortunately, inside `signed_in_root_path` the scope is not like I would like to have it. In [this line](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/controllers/helpers.rb#L171) the `scope == :admin`, which leads to looking for `admin_root_path` (see the missing s).

Maybe this is not often the use case, but we have it right now.
I do have a workaround by adding a new route with name `admin_root` which leads to the correct root. But I don't think that this is really the best way to handle it.

If you need any further information I will gladly provide it.

Thanks

**Comment by tegon** [comment] 2017-12-20 02:11
Hello @mobilutz, thanks for the report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-01-04 12:52
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-01-04 12:52 UTC
Labels: Needs more info

**Comment by mobilutz** [comment] 2018-01-04 12:53
Ok, then I will open it again ...
