### ISSUE TITLE
Omniauth for github not working

### ISSUE THREAD

**Issue by psantos10** [plataformatec/devise#4743] opened 2018-01-03 08:49 UTC
## Environment

- Ruby **2.5.0-p0**
- Rails **5.2.0.beta2**
- Devise **4.4.0**

## Current behavior

I setup Omniauth for authentication with github. So in `config/initializers/devise.rb` I include this line: 

`config.omniauth :github, 'MY_REAL_CLIENT_ID_HERE', 'MY_REAL_CLIENT_SECRET_HERE', scope: 'user,public_repo'`

## Expected behavior

Expect to work properly, but I am getting a  "page not found" error on Github. Looking on the URL, I see that the CLIENT_ID are not sent. `https://github.com/login/oauth/authorize?client_id&redirect_uri= ...`

But if I change to: 

`config.omniauth :github, 'APP_ID', 'APP_SECRET', scope: 'user,public_repo'`

The client ID will be sent as `APP_ID` : `https://github.com/login/oauth/authorize?client_id=APP_ID&redirect_uri= ...`

**Comment by psantos10** [comment] 2018-01-03 11:02
I noticed now that when I pass a CLIENT_ID which starts with a number like `3ddfld...` it won't work.

But if it starts with a String like `d3dff...` ... it will work. 

Is this behavior expected?

**Comment by tegon** [comment] 2018-01-03 23:11
Hello @psantos10, thanks for your report.
I'm not sure if this is a Devise bug, it seems to be on https://github.com/omniauth/omniauth-github 🤔 

Anyway, can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by tegon** [comment] 2018-02-15 13:20
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.

Thank you!

**Closed by tegon** 2018-02-15 13:20 UTC
Labels: Needs more info
