### ISSUE TITLE
Using Devise Confirmable with Poltergeist breaks tests 

### ISSUE THREAD

**Issue by seyonv** [plataformatec/devise#4479] opened 2017-03-29 16:05 UTC
Apologies in advance if this is the wrong place to post this. Thought people using Devise and confirmable may have the best insight with this

Essentially an integration test breaks when going through the signup process. It works perfectly when using Selenium but fails when using Poltergeist (unless sleep 0.5 is added, in which case it works).

The test seems to hang right BEFORE the below line is executed. Sleep Conditions are bad to have in the test suite and was wondering whether there was anyway to explicitly wait for the below line to be executed in RSpec/Capybara.

More importantly, could anyone explain why the headless browser(poltergeist) would fail but not Selenium as a result of rendering the confirmation_instructions? The explicit redirect is to a new page of course

`Rendered devise/mailer/confirmation_instructions.html.erb (0.8ms)`

**Comment by darrenterhune** [comment] 2017-11-15 20:46
We use `rails 5.0.1` and `devise ~> 4.2` with `poltergeist ~> 1.12` with `phantomjs 2.1.1` and do not have issues with confirmable. Maybe some example code would help.

**Comment by rafaelfranca** [comment] 2017-11-22 21:44
Closing since we can't reproduce. Let us know if you are able to provide more information

**Closed by rafaelfranca** 2017-11-22 21:44 UTC
