### ISSUE TITLE
after_sign_out_path_for is never called

### ISSUE THREAD

**Issue by Sollace** [plataformatec/devise#4443] opened 2017-02-26 09:48 UTC
I'm using devise 4.2.0 (rails 4.2.7.1) and have been trying to get it to redirect in some kind of sane way.

The following works for signing in:

      after_filter :store_last_location, if: :not_devise_controller?
      def store_last_location
        return unless request.get?
        session["user_return_to"] = request.fullpath
      end
      def after_sign_in_path_for(resource)
        puts "user_return_to: "
        puts  session["user_return_to"]
        session["user_return_to"] || root_path
      end
  
But nothing I've tried works for signing _out_. It always just goes back to root anyway.

      def stored_location_for(resource)
        nil
        #doesn't work either
        #request.referrer
      end
      
      def after_sign_out_path_for(resource)
        puts "user_return_to (out): "
        puts  request.referrer
        request.referrer
      end

The apparent lack of my logging messages also shows it _doesn't even get to_ after_sign_out_path_for.

Am I doing something wrong here? Is this code not supposed to go into ApplicationController?

I also tried generating device controllers to override sessions, but Devise just started catching fire with a "Users is not defined" error when you try to log in.

**Comment by Mechasparrow** [comment] 2017-05-24 22:42
same situation

**Comment by larryisthere** [comment] 2017-11-19 16:04
@Sollace As https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update explained. 

> request.referer is set by the value of the HTTP referer header. Many browsers do not send this header. Therefore the only robust cross-browser way to implement this functionality is by using the session.

Just try the way this article use.

**Comment by ncri** [comment] 2017-12-02 11:11
The issue is that the session is deleted when signing out so the stored location is lost.

For me this in the application controller works:

```
def after_sign_out_path_for(resource_or_scope)
  request.referer
end
```

For redirecting after signing in the instructions here work: https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

However, the Wiki is plain wrong here for signing out. Maybe it is just outdated? This part should be fixed in the Wiki:

> To redirect to the stored location after the user signs out you would override the `after_sign_out_path_for` method:
> 
> ```
> def after_sign_out_path_for(resource_or_scope)
>   stored_location_for(resource_or_scope) || super
> end
> ```

**Comment by tegon** [comment] 2018-01-17 13:47
Hello @ncri, thanks for digging into this.
Seems to me that the wiki was referring to the Devise's implementation of the `after_sign_out_path_for` - which already changed a lot, btw.
Feel free to update the wiki. It is maintained by the community, so if there aren't any up to date instructions, we recommend you contribute your findings back.

Thank you!

**Closed by tegon** 2018-01-17 13:47 UTC
