### ISSUE TITLE
Scopes starting with ":find_by_" crash app before creating DB

### ISSUE THREAD

**Issue by efojs** [plataformatec/devise#5104] opened 2019-07-26 16:23 UTC
I've ran into it few days ago(#5103) and [found workaround](https://www.reddit.com/r/rails/comments/chtk5l/model_scopes_and_db_tables/) (=> create table and only then declare scopes).   

But now, after some feedback on Reddit, I dug that problem is in **specific scope naming in devise-generated/connected models.**

## Environment
- Ruby **2.5.5**
- Rails **6.1.0.alpha**
- Devise **master branch**

## Current behavior
I've made a [repo with sucess and fail steps](https://github.com/efojs/scope-test). In few words:
* Before creating DB:
* Declaring scope starting with `:find_by_` in devise-generated User model and
* Running `$ rails c` **crashes** => `FATAL: database "scope_test_development" does not exist`  
* Same with **initial** deploy to Heroku: **crashes** => `ERROR:  relation "users" does not exist`

BUT:
* Declaring scope starting with `:find_by_` in custom generated model and
* Running `$ rails c` **starts console** => `2.5.5 :001 >` 

ELSE BUT:
* Declaring scope starting with `:get_by_` in devise-generated User model and
* Running `$ rails c` **starts console** => `2.5.5 :001 >` 

## Expected behavior
* Declaring scope starting with `:find_by_` in devise-generated User model and
* Running `$ rails c` **starts console** => `2.5.5 :001 >` 

---
IDK, maybe there are some other names that can cause it.

**Comment by tegon** [comment] 2019-08-01 18:51
That's odd, I did the first step (uncomment the scope in `shirt.rb`) and things broke right the way:
<img width="982" alt="Screen Shot 2019-08-01 at 15 36 03" src="https://user-images.githubusercontent.com/3727827/62318507-5f522080-b472-11e9-9bf4-32899d336d64.png">

My guess is that by using `find_by` Rails thinks that the method is a dynamic finder (like `find_by_name` but it doesn't know whether `name` is an actual column of that database table or not. So it has to perform a query to retrieve the table columns.
I've tested that in a console (with the scope commented):
<img width="1211" alt="Screen Shot 2019-08-01 at 15 49 24" src="https://user-images.githubusercontent.com/3727827/62319263-f53a7b00-b473-11e9-9e8d-bf61c50d643b.png">
You can see that `#foo` raises `NoMethodError`, while anything followed by the prefix `find_by_` raises `ActiveRecord::NoDatabaseError`.

I'm going to close this since it seems like the expected behavior.

**Closed by tegon** 2019-08-01 18:51 UTC

**Comment by efojs** [comment] 2019-08-01 19:27
It's odd. I remember that I read somewhere that `find_by_...` and `find_by_...!` were deprecated.
But now all I can find is that it's clearly said in docs that these are [dynamic methods](https://edgeguides.rubyonrails.org/active_record_querying.html#dynamic-finders):

> For every field (also known as an attribute) you define in your table, Active Record provides a finder method. If you have a field called first_name on your Client model for example, you get `find_by_first_name` for free from Active Record. If you have a locked field on the Client model, you also get `find_by_locked` method.

Excuse me for wasting your time. Thank you. My bad.

**Comment by tegon** [comment] 2019-08-01 19:31
No problem, I also thought they were removed, but it seems like they're still there, although they're deprecated.
