### ISSUE TITLE
NoMethodError in Users::SessionsController#new

### ISSUE THREAD

**Issue by alexvirtualbr** [plataformatec/devise#4943] opened 2018-09-25 15:01 UTC
Hi Guys,

I have a problem here when I try do a login or a register.

routes.rb :
 devise_for :users, :controllers => { 
    sessions: "users/sessions", 
    registrations: "users/registrations",    
    omniauth_callbacks: "omniauth_callbacks"
  }  
  as :user do
    get 'login' => 'users/sessions#new', :as => "login"
    get 'signup' => 'users/registrations#new', :as => "signup"
    delete 'signout' => 'users/sessions#destroy', :as => "signout"
  end    

navbar (layout/view):
<%= link_to t("navbar.signin"), login_path, class: "nav-link" %>

model:
class User < ApplicationRecord:
     devise :database_authenticatable, :registerable,  :recoverable, :rememberable, :validatable, 
                 :omniauthable
end

## Environment

- Ubuntu 18.04 LTS
- Ruby 2.6.0-preview2
- Rails 5.2.0
- Devise 4.5.0

## Current behavior

NoMethodError in Users::SessionsController#new
"protected method `render' called for #<Users::SessionsController:0x00007fc6280c7e70> Did you mean? responder"

####################################################################
responders (2.4.0) lib/action_controller/responder.rb:238:in `default_render'
responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
devise (4.5.0) app/controllers/devise/sessions_controller.rb:14:in `new'
actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (5.2.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'

The SessionController I didn't changes and I don't definition a render method in anywhere.

Please, help me.

Thanks, so much.

**Comment by feliperenan** [comment] 2018-09-25 15:21
Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.

**Comment by alexvirtualbr** [comment] 2018-09-25 15:36
> Could you please provide us a sample application that reproduces the issue in isolation?
> 
> That would help us find the issue.

Hi @feliperenan the code this app is a private directory in Bitbucket. But i have one idea where this generation this error. For me, is a conflit between gems. So, I'm observe a gem responders-2.4.0 (maybe was dependency installed):

I found this:
def to_html
    default_render
    rescue ActionView::MissingTemplate => e
      navigation_behavior(e)
end

 # If a response block was given, use it, otherwise call render on controller.
    
    def default_render
      if @default_response
        @default_response.call(options)
      else
        controller.render(options)
      end
    end

**Comment by feliperenan** [comment] 2018-09-25 22:05
Ok. So I'm gonna close this one since it seems not be a Devise issue. 

If you think it's a Devise issue, please give more information on how to reproduce it then we reopen this one.

Thanks

**Closed by feliperenan** 2018-09-25 22:05 UTC

**Comment by alexvirtualbr** [comment] 2018-09-26 01:03
@feliperenan, maybe I don't have used the right words to explain to you that answer gem is a dependency of Devise that uses it internally.

**Comment by feliperenan** [comment] 2018-09-26 13:06
Can you give the steps for us to reproduce the issue? 

Will be even more helpful if you provide a sample application or a test case that reproduces the error. it doesn't need to be a complete app, just an app with Devise configured that reproduces the issue that you are facing.

**Comment by alexvirtualbr** [comment] 2018-09-26 15:30
@feliperenan when i try reproduce it in another app test it isn't happened so must be a conflit between gems.
