### ISSUE TITLE
Ruby 2.2.6 - wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by NILID** [plataformatec/devise#4465] opened 2017-03-11 22:08 UTC
I can not overcome the following problem in any way (using Ruby 2.2.6 ):

ArgumentError at /en/users/password
wrong number of arguments (0 for 1)

```
    def filtered_hash_by_method_for_given_keys(conditions, method, condition_keys)
      condition_keys.each do |k|
        value = conditions[k]
>>      conditions[k] = value.send(method) if value.respond_to?(method)
      end
      conditions
    end
```

Local Variables:
```
k	              :email
value                  nil
conditions            {:reset_password_token=>"oD4v2yDk5re45MYahFS7"}
method	              :strip
condition_keys        [:email]
```
As I understand it, the send(method) can not be called for value (which equal nil).

When I use ruby 1.9.3,  There are no errors.

I use:
ruby (2.2.6)
rails (3.2.22)
devise (3.5.10)

**Comment by carlosantoniodasilva** [comment] 2017-03-13 11:51
Can you please provide a sample application that reproduces the problem? I can't see anything wrong at a glance. Thanks.

**Comment by tegon** [comment] 2017-12-07 16:29
I'm closing this issue because it has not had recent activity.
If you're still facing this on the latest version, please open a new one with all the information requested in the template.
Thank you!

**Closed by tegon** 2017-12-07 16:29 UTC
Labels: Needs more info
